"use client";
import{useEffect,useMemo,useState}from"react";
import{PageHeader}from"@/components/ui/PageHeader";
import{useAuth}from"@/features/auth/AuthProvider";
import{canManageTrainingObjectives}from"@/features/auth/types";
import{subscribeStudents}from"@/features/students/firestore";
import type{Student}from"@/features/students/types";
import{VISIBLE_OFFICIAL_PROGRAMS}from"@/features/programs/modularPrograms";
import{subscribeManagedPrograms,type ManagedTrainingProgram}from"@/features/programs/management";
import{subscribeTrainingProgressObjectives}from"@/features/training-progress/objectives";
import{compareTrainingPrograms,type TrainingProgressMilestone}from"@/features/programs/types";
import{CohortTrainingObjectivesPanel}from"@/features/training-progress/CohortTrainingObjectivesPanel";
import{saveTrainingCohort,subscribeTrainingCohorts}from"./firestore";
import type{TrainingCohort}from"./types";

const blank=(uid=""):TrainingCohort=>({id:"",name:"",programId:"",startDate:new Date().toISOString().slice(0,10),status:"Planifiée",studentIds:[],createdBy:uid,createdAt:"",updatedBy:uid,updatedAt:""});
export function TrainingCohortsPage(){
 const{profile}=useAuth(),canEdit=canManageTrainingObjectives(profile),[cohorts,setCohorts]=useState<TrainingCohort[]>([]),[students,setStudents]=useState<Student[]>([]),[managed,setManaged]=useState<ManagedTrainingProgram[]>([]),[objectives,setObjectives]=useState<TrainingProgressMilestone[]>([]),[selectedId,setSelectedId]=useState(""),[draft,setDraft]=useState<TrainingCohort>(()=>blank(profile?.uid)),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{const fail=(value:Error)=>setError(value.message),off=[subscribeTrainingCohorts(setCohorts,fail),subscribeStudents({next:setStudents,error:fail}),subscribeManagedPrograms(setManaged,fail),subscribeTrainingProgressObjectives(setObjectives,fail)];return()=>off.forEach(item=>item())},[]);
 const programs=useMemo(()=>[...new Map([...VISIBLE_OFFICIAL_PROGRAMS,...managed.filter(item=>item.catalogKind==="program"&&item.status!=="inactive")].map(item=>[item.id,item])).values()].sort(compareTrainingPrograms),[managed]),selected=cohorts.find(item=>item.id===selectedId),selectedProgram=programs.find(item=>item.id===selected?.programId),toggle=(id:string)=>setDraft(current=>({...current,studentIds:current.studentIds.includes(id)?current.studentIds.filter(value=>value!==id):[...current.studentIds,id]}));
 function edit(value?:TrainingCohort){setDraft(value?{...value,studentIds:[...value.studentIds]}:blank(profile?.uid));setSelectedId(value?.id||"");setError("");setMessage("")}
 async function save(){try{setError("");const now=new Date().toISOString(),actor=profile?.uid||"",value={...draft,id:draft.id||`cohorte-formation-${Date.now()}`,createdBy:draft.createdBy||actor,createdAt:draft.createdAt||now,updatedBy:actor,updatedAt:now};await saveTrainingCohort(value);setSelectedId(value.id);setDraft(value);setMessage("Cohorte enregistrée.")}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible")}}
 if(!canEdit)return <section className="card access-denied"><h1>Accès refusé</h1><p>La gestion des cohortes est réservée à la Direction et au Chef instructeur.</p></section>;
 return <><PageHeader title="Cohortes" subtitle="Groupes de formation, étudiants et objectifs communs"/>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}<section className="card training-cohort-table"><div className="section-heading"><div><h2>Liste des cohortes</h2><p>{cohorts.length} cohorte(s)</p></div><button className="button" onClick={()=>edit()}>+ Créer une cohorte</button></div><div className="progress-table-wrap"><table><thead><tr><th>Nom</th><th>Programme</th><th>Date début</th><th>Étudiants</th><th>Statut</th><th>Action</th></tr></thead><tbody>{cohorts.map(item=><tr key={item.id} onClick={()=>edit(item)}><td><strong>{item.name}</strong></td><td>{programs.find(program=>program.id===item.programId)?.name||item.programId}</td><td>{item.startDate}</td><td>{item.studentIds.length}</td><td><span className="badge">{item.status}</span></td><td><button className="button secondary small" onClick={event=>{event.stopPropagation();edit(item)}}>Ouvrir</button></td></tr>)}{!cohorts.length&&<tr><td colSpan={6}>Aucune cohorte de formation.</td></tr>}</tbody></table></div></section><section className="card theory-form"><h2>{draft.id?`Modifier ${draft.name}`:"Créer une cohorte"}</h2><div className="form-grid"><label>Nom<input required value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder="Ex. ATP-A Septembre 2026"/></label><label>Programme<select required value={draft.programId} onChange={event=>setDraft({...draft,programId:event.target.value})}><option value="">Sélectionner</option>{programs.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Date de début<input required type="date" value={draft.startDate} onChange={event=>setDraft({...draft,startDate:event.target.value})}/></label><label>Date de fin<input type="date" value={draft.endDate||""} onChange={event=>setDraft({...draft,endDate:event.target.value||undefined})}/></label><label>Statut<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value as TrainingCohort["status"]})}>{["Planifiée","Active","Terminée","Archivée"].map(item=><option key={item}>{item}</option>)}</select></label></div><fieldset><legend>Étudiants associés — {draft.studentIds.length}</legend><div className="theory-student-list">{students.map(item=><label key={item.id}><input type="checkbox" checked={draft.studentIds.includes(item.id)} onChange={()=>toggle(item.id)}/>{item.firstName} {item.lastName}</label>)}</div></fieldset><div className="form-actions"><button className="button" disabled={!draft.name.trim()||!draft.programId||!draft.startDate} onClick={save}>Enregistrer la cohorte</button>{draft.id&&<button className="button secondary" onClick={()=>edit()}>Nouvelle cohorte</button>}</div></section>{selected&&selectedProgram&&<CohortTrainingObjectivesPanel cohortId={selected.id} cohortName={selected.name} program={selectedProgram} objectives={objectives}/>}</>;
}
