"use client";
import {useState} from "react";
import type{Aircraft,MaintenanceTask}from"@/features/fleet/types";
import{saveMaintenanceTask}from"@/features/fleet/firestore";
import{archiveCalendarPdf,compareCalendar,readMaintenanceCalendar,type CalendarAircraftType,type CalendarChange}from"./calendarImport";

export function CalendarImportModal({aircraft,tasks,actor,onClose,onComplete}:{aircraft:Aircraft[];tasks:MaintenanceTask[];actor:{id:string;name:string;role:string};onClose:()=>void;onComplete:(message:string)=>void}){
 const[type,setType]=useState<CalendarAircraftType>("C152"),[file,setFile]=useState<File|null>(null),[revision,setRevision]=useState(""),[progress,setProgress]=useState(""),[error,setError]=useState(""),[changes,setChanges]=useState<CalendarChange[]>([]),[selected,setSelected]=useState<Set<number>>(new Set()),[working,setWorking]=useState(false);
 async function analyze(){if(!file){setError("Sélectionnez un calendrier PDF.");return}setWorking(true);setError("");setChanges([]);try{const result=await readMaintenanceCalendar(file,setProgress);setRevision(result.revision);const found=compareCalendar(result.text,type,aircraft,tasks);setChanges(found);setSelected(new Set(found.map((item,index)=>item.manual?-1:index).filter(index=>index>=0)));setProgress(found.length?`${found.length} changement(s) détecté(s). Vérifiez-les avant confirmation.`:"Aucun changement fiable détecté. Le calendrier doit être vérifié manuellement.")}catch(value){setError(value instanceof Error?value.message:"Analyse impossible.")}finally{setWorking(false)}}
 async function apply(){if(!file)return;if(!revision.trim()){setError("La révision du calendrier est obligatoire.");return}const chosen=changes.filter((_,index)=>selected.has(index));if(!chosen.length){setError("Sélectionnez au moins un changement calculable.");return}setWorking(true);setError("");try{await archiveCalendarPdf(file,type,revision.trim());for(let index=0;index<chosen.length;index++){const item=chosen[index];setProgress(`Application ${index+1} sur ${chosen.length} — ${item.aircraft.registration} · ${item.task.title}`);await saveMaintenanceTask(item.updated,actor,`Import du calendrier ${type}, révision ${revision.trim()} (${file.name})`,item.aircraft.registration)}onComplete(`${chosen.length} changement(s) du calendrier ${type} révision ${revision.trim()} appliqués et historisés.`);onClose()}catch(value){setError(`Import interrompu : ${value instanceof Error?value.message:"erreur inconnue"}`)}finally{setWorking(false)}}
 return <div className="modal-backdrop maintenance-calendar-import-backdrop"><section className="modal maintenance-calendar-import"><header><div><h2>Importer un calendrier de maintenance</h2><p>OCR local · comparaison et validation obligatoires</p></div><button className="icon-button" disabled={working} onClick={onClose}>×</button></header><div className="modal-body">{error&&<div className="notice error" role="alert">{error}</div>}{progress&&<div className="notice" role="status">{progress}</div>}<div className="form-grid"><label>Type d’avion<select value={type} disabled={working} onChange={event=>setType(event.target.value as CalendarAircraftType)}><option>C152</option><option>C172</option><option>PA31</option></select></label><label>Révision détectée<input value={revision} placeholder="Détectée après analyse" onChange={event=>setRevision(event.target.value)}/></label></div><label>Calendrier approuvé par Transports Canada<input type="file" accept="application/pdf,.pdf" disabled={working} onChange={event=>{setFile(event.target.files?.[0]||null);setChanges([]);setError("");setProgress("")}}/></label>{changes.length>0&&<div className="calendar-change-list"><div className="calendar-change-head"><strong>Changements proposés</strong><span>{selected.size} sélectionné(s)</span></div>{changes.map((item,index)=><label className={`calendar-change ${item.manual?"manual":""}`} key={`${item.aircraft.id}-${item.task.id}`}><input type="checkbox" disabled={item.manual||working} checked={selected.has(index)} onChange={event=>setSelected(current=>{const next=new Set(current);event.target.checked?next.add(index):next.delete(index);return next})}/><span><strong>{item.aircraft.registration} · {item.task.title}</strong><small>{item.previous}</small><b>→ {item.next}</b>{item.manual&&<em>Vérification manuelle requise : dernière exécution manquante. Aucune modification automatique.</em>}</span></label>)}</div>}<p className="calendar-import-warning">Le PDF et la révision sont archivés localement. Chaque tâche confirmée produit une entrée d’historique distincte. Les tâches sans dernière date ou dernier Air Time restent inchangées.</p></div><footer><button className="button secondary" disabled={working} onClick={onClose}>Annuler</button><button className="button secondary" disabled={working||!file} onClick={analyze}>{working?"Traitement…":"Analyser le PDF"}</button><button className="button" disabled={working||!changes.length} onClick={apply}>Confirmer et appliquer</button></footer></section></div>
}
