import type{TrainingProgram,TrainingProgressMilestone}from"@/features/programs/types";
import type{ProgressActivity,ProgressLesson,ProgressStatus,ProgressThresholds}from"./types";
export const DEFAULT_PROGRESS_THRESHOLDS:ProgressThresholds={inactiveWarningDays:7,inactiveCriticalDays:14,watchGapPercent:5,lateGapPercent:10,criticalGapPercent:20};
const day=(value:string)=>Date.parse(`${value}T00:00:00Z`)/86400000;
const round=(value:number)=>Math.round(value*10)/10;
const phaseNumber=(value:string)=>value.match(/\d+/)?.[0]||"";
const planNumber=(value:string)=>value.match(/(?:^|-)L(\d+)(?:-|$)/i)?.[1]||value.match(/(?:lesson|lecon)-(\d+)/i)?.[1]||value.match(/\d+/)?.[0]||"";
export const activityHours=(item:ProgressActivity)=>item.status!=="Complété"?0:item.type==="Double commande"||item.type==="Solo"?item.hobbsStart!==undefined&&item.hobbsEnd!==undefined?Math.max(0,item.hobbsEnd-item.hobbsStart):(item.airtimeMinutes||0)/60:item.groundTimeHours??Math.max(0,item.endMinutes-item.startMinutes)/60;
export const plannedActivityHours=(item:ProgressActivity)=>item.status==="Annulé"?0:Math.max(0,item.endMinutes-item.startMinutes)/60;

export function calculatePhasePlan(program:TrainingProgram|undefined,phaseId:string){
 const lessons=program?.lessons.filter(item=>String(item.phase)===phaseId)||[],hours=lessons.flatMap(item=>item.components).reduce((sum,item)=>({flight:sum.flight+(item.hours.doubleCommande||0)+(item.hours.solo||0),ground:sum.ground+(item.hours.sol||0),simulator:sum.simulator+(item.hours.dev||0)}),{flight:0,ground:0,simulator:0});
 return{phaseId,phaseName:program?.phases.find(item=>String(item.number)===phaseId)?.name||`Phase ${phaseId}`,lessonNumbers:new Set(lessons.map(item=>String(item.number))),lessonCount:lessons.length,flightHours:round(hours.flight),groundHours:round(hours.ground),simulatorHours:round(hours.simulator),totalHours:round(hours.flight+hours.ground+hours.simulator)};
}

export function milestonesForCohort(values:TrainingProgressMilestone[],cohortId:string){
 return resolveTrainingObjectives(values,cohortId,"");
}
export type AppliedTrainingObjective=TrainingProgressMilestone&{appliedSource:string};
export function resolveTrainingObjectives(values:TrainingProgressMilestone[],cohortId:string,studentId:string,cohortName=""):AppliedTrainingObjective[]{
 const key=(item:TrainingProgressMilestone)=>[item.phaseId||"programme",item.milestoneType,item.title.trim().toLowerCase()].join("|"),result=new Map<string,AppliedTrainingObjective>();
 values.filter(item=>item.scope==="cohort"&&item.cohortId===cohortId).forEach(item=>result.set(key(item),{...item,appliedSource:cohortName?`Cohorte ${cohortName}`:"Objectif cohorte"}));
 values.filter(item=>item.scope==="student"&&item.studentId===studentId).forEach(item=>result.set(key(item),{...item,appliedSource:"Personnalisation étudiant"}));return[...result.values()];
}

export function calculateTrainingProgressStatus(input:{actualPercent:number;expectedPercent:number|null;daysInactive:number|null;deadlineIssue?:{severity:"warning"|"critical";reason:string;action:string}},thresholds=DEFAULT_PROGRESS_THRESHOLDS):{status:ProgressStatus;reason:string;action:string}{
 const{actualPercent,expectedPercent,daysInactive,deadlineIssue}=input;if(deadlineIssue)return{status:deadlineIssue.severity==="critical"?"En retard":"À surveiller",reason:deadlineIssue.reason,action:deadlineIssue.action};
 if(daysInactive!==null&&daysInactive>=thresholds.inactiveCriticalDays)return{status:"Critique",reason:`${daysInactive} jours sans activité complétée`,action:"Planifier une rencontre instructeur/étudiant et réviser le calendrier de formation."};
 if(expectedPercent===null)return{status:daysInactive!==null&&daysInactive>=thresholds.inactiveWarningDays?"À surveiller":"Non configuré",reason:"Aucune date cible administrative pour la phase actuelle",action:"La progression réelle reste calculée; ajouter une date de phase dans Programmes si un rythme calendrier est requis."};
 const gap=actualPercent-expectedPercent;if(gap<=-thresholds.lateGapPercent)return{status:"En retard",reason:`Progression réelle ${actualPercent} %, rythme attendu ${expectedPercent} % — écart de ${round(gap)} %`,action:"Réviser le rythme de formation avec l’instructeur principal."};if(gap<=-thresholds.watchGapPercent||daysInactive!==null&&daysInactive>=thresholds.inactiveWarningDays)return{status:"À surveiller",reason:daysInactive!==null&&daysInactive>=thresholds.inactiveWarningDays?`${daysInactive} jours sans activité`:`Progression réelle ${actualPercent} %, rythme attendu ${expectedPercent} %`,action:"Planifier une activité dans les prochains jours."};if(gap>=thresholds.watchGapPercent)return{status:"En avance",reason:`Progression réelle ${actualPercent} %, rythme attendu ${expectedPercent} %`,action:"Maintenir le rythme de formation."};return{status:"Conforme",reason:`Progression réelle ${actualPercent} %, rythme attendu ${expectedPercent} %`,action:"Maintenir le rythme de formation."};
}
export const calculateStudentProgressStatus=calculateTrainingProgressStatus;

export function calculateProgress(input:{studentId:string;startDate:string;program?:TrainingProgram;lessons:ProgressLesson[];activities:ProgressActivity[];milestones:TrainingProgressMilestone[];today?:string}){
 const today=input.today||new Date().toISOString().slice(0,10),datedMilestones=input.milestones.map(item=>{if(item.targetDate||item.targetDaysAfterStart===undefined||!input.startDate)return item;const date=new Date(`${input.startDate}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+item.targetDaysAfterStart);return{...item,targetDate:date.toISOString().slice(0,10)}}),lessons=input.lessons.filter(item=>item.studentId===input.studentId),completedLessons=lessons.filter(item=>item.status==="Réussi").length,totalLessons=input.program?.lessons.length||lessons.length,studentActivities=input.activities.filter(item=>item.studentId===input.studentId||item.participantStudentIds.includes(input.studentId)),completedActivities=studentActivities.filter(item=>item.status==="Complété"),actualHours=round(completedActivities.reduce((sum,item)=>sum+activityHours(item),0)),lastActivity=completedActivities.map(item=>item.date).filter(Boolean).sort().at(-1)||"",daysInactive=lastActivity?Math.max(0,Math.round(day(today)-day(lastActivity))):input.startDate?Math.max(0,Math.round(day(today)-day(input.startDate))):null;
 const phases=input.program?.phases||[],currentPhase=phases.find(phase=>{const phaseLessons=lessons.filter(item=>phaseNumber(item.phase)===String(phase.number));return phaseLessons.length===0||phaseLessons.some(item=>item.status!=="Réussi")})||phases.at(-1),currentPhaseId=currentPhase?String(currentPhase.number):phaseNumber(lessons.find(item=>item.status!=="Réussi")?.phase||lessons.at(-1)?.phase||"1"),phasePlan=calculatePhasePlan(input.program,currentPhaseId),phaseLessons=lessons.filter(item=>phaseNumber(item.phase)===currentPhaseId),completedPhaseLessons=phaseLessons.filter(item=>item.status==="Réussi").length,linkedReservationIds=new Set(phaseLessons.map(item=>item.linkedReservationId).filter(Boolean)),phaseActivities=completedActivities.filter(item=>linkedReservationIds.has(item.id)||(item.lessonPlanId&&phasePlan.lessonNumbers.has(planNumber(item.lessonPlanId)))),phaseActualHours=round(phaseActivities.reduce((sum,item)=>sum+activityHours(item),0)),lessonProgress=phasePlan.lessonCount?completedPhaseLessons/phasePlan.lessonCount*100:null,hourProgress=phasePlan.totalHours?phaseActualHours/phasePlan.totalHours*100:null,progressAxes=[lessonProgress,hourProgress].filter((value):value is number=>value!==null),actualPercent=progressAxes.length?Math.min(100,Math.round(progressAxes.reduce((sum,value)=>sum+value,0)/progressAxes.length)):0;
 const phaseMilestone=datedMilestones.filter(item=>item.phaseId===currentPhaseId&&item.milestoneType==="Fin de phase"&&item.targetDate).sort((a,b)=>(a.targetDate||"").localeCompare(b.targetDate||""))[0],previousTarget=datedMilestones.filter(item=>item.milestoneType==="Fin de phase"&&item.phaseId&&Number(item.phaseId)<Number(currentPhaseId)&&item.targetDate).sort((a,b)=>(b.targetDate||"").localeCompare(a.targetDate||""))[0]?.targetDate,startBoundary=previousTarget||input.startDate,expectedPercent=phaseMilestone?.targetDate&&startBoundary?Math.max(0,Math.min(100,Math.round((day(today)-day(startBoundary))/(day(phaseMilestone.targetDate)-day(startBoundary))*100))):null,phaseComplete=phasePlan.lessonCount>0&&completedPhaseLessons>=phasePlan.lessonCount;
 const administrativeOverdue=datedMilestones.filter(item=>item.required&&item.targetDate&&item.targetDate<today&&item.milestoneType!=="Fin de phase").sort((a,b)=>(a.targetDate||"").localeCompare(b.targetDate||""))[0];let deadlineIssue:{severity:"warning"|"critical";reason:string;action:string}|undefined;
 if(phaseMilestone?.targetDate&&phaseMilestone.targetDate<today&&!phaseComplete){const late=Math.round(day(today)-day(phaseMilestone.targetDate));deadlineIssue={severity:"critical",reason:`${phasePlan.phaseName} devait être terminée depuis ${late} jour${late===1?"":"s"} — progression actuelle ${actualPercent} %`,action:"Réviser le dossier de phase et le calendrier de formation."};}else if(administrativeOverdue)deadlineIssue={severity:"warning",reason:`Échéance « ${administrativeOverdue.title} » dépassée depuis ${Math.round(day(today)-day(administrativeOverdue.targetDate!))} jour(s)`,action:"Vérifier et consigner le suivi administratif de cet événement."};
 const baseStatus=calculateTrainingProgressStatus({actualPercent,expectedPercent,daysInactive,deadlineIssue}),nextMilestone=datedMilestones.filter(item=>item.targetDate&&item.targetDate>=today).sort((a,b)=>(a.targetDate||"").localeCompare(b.targetDate||""))[0],status=nextMilestone&&"appliedSource" in nextMilestone?{...baseStatus,reason:`${baseStatus.reason} · Objectif appliqué : ${nextMilestone.appliedSource}`} :baseStatus;
 return{completedLessons,totalLessons,actualHours,actualPercent,expectedPercent,gap:expectedPercent===null?null:actualPercent-expectedPercent,lastActivity,daysInactive,status,nextMilestone,currentPhaseId,currentPhaseName:phasePlan.phaseName,plannedHours:phasePlan.totalHours,plannedFlightHours:phasePlan.flightHours,plannedGroundHours:phasePlan.groundHours,plannedSimulatorHours:phasePlan.simulatorHours,realizedHours:phaseActualHours,plannedLessons:phasePlan.lessonCount,completedPhaseLessons};
}
