"use client";
import{useState}from"react";
import{useAuth}from"@/features/auth/AuthProvider";
import{canManageTrainingObjectives}from"@/features/auth/types";
import type{TrainingProgram,TrainingProgressMilestone}from"@/features/programs/types";
import{resolveTrainingObjectives}from"./calculations";
import{saveTrainingProgressObjective}from"./objectives";

const cohortObjectiveTypes=["Fin de phase","Examen","Évaluation","Remise de notes"]as const;
export function CohortTrainingObjectivesPanel({cohortId,cohortName,program,objectives}:{cohortId:string;cohortName:string;program:TrainingProgram;objectives:TrainingProgressMilestone[]}){
 const{profile}=useAuth(),canEdit=canManageTrainingObjectives(profile),[open,setOpen]=useState(false),[phaseId,setPhaseId]=useState(String(program.phases[0]?.number||"")),[title,setTitle]=useState(""),[type,setType]=useState<TrainingProgressMilestone["milestoneType"]>("Fin de phase"),[date,setDate]=useState(""),[notes,setNotes]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState("");
 const programObjectives=objectives.filter(item=>item.programId===program.id),applied=resolveTrainingObjectives(programObjectives,cohortId,"",cohortName),ready=Boolean(title.trim()&&phaseId&&date&&notes.trim()&&reason.trim());
 async function save(){if(!ready)return;try{setError("");const now=new Date().toISOString(),actor=profile?.uid||"",id=`objectif-cohorte-${cohortId}-${Date.now()}`,value:TrainingProgressMilestone={id,scope:"cohort",programId:program.id,cohortId,phaseId,title:title.trim(),milestoneType:type,targetDate:date,required:true,notes:notes.trim(),createdBy:actor,createdAt:now,updatedBy:actor,updatedAt:now};await saveTrainingProgressObjective(value,programObjectives,{author:actor,reason});setOpen(false);setTitle("");setDate("");setNotes("");setReason("")}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible")}}
 return <section className="card cohort-training-objectives"><header><div><h2>Objectifs de progression — {cohortName}</h2><p className="muted">Objectifs communs de la cohorte. Les heures et les leçons proviennent automatiquement du programme.</p></div>{canEdit&&<button className="button secondary" onClick={()=>setOpen(value=>!value)}>+ Objectif cohorte</button>}</header>{error&&<div className="notice error">{error}</div>}<div className="milestone-list">{applied.map(item=><article key={item.id}><div><span className="badge">{item.appliedSource}</span><strong>{item.title}</strong><small>Phase {item.phaseId}</small></div><p>Date cible : <b>{item.targetDate}</b></p>{item.notes&&<small>{item.notes}</small>}</article>)}{!applied.length&&<p>Aucun objectif configuré pour cette cohorte.</p>}</div>{open&&<div className="program-form-grid"><label className="wide">Titre<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Programme<input value={program.name} readOnly/></label><label>Phase associée<select required value={phaseId} onChange={event=>setPhaseId(event.target.value)}><option value="">Sélectionner</option>{program.phases.map(item=><option key={item.number} value={String(item.number)}>Phase {item.number} — {item.name}</option>)}</select></label><label>Type<select value={type} onChange={event=>setType(event.target.value as TrainingProgressMilestone["milestoneType"])}>{cohortObjectiveTypes.map(item=><option key={item}>{item}</option>)}</select></label><label>Date cible<input required type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="wide">Notes<textarea required value={notes} onChange={event=>setNotes(event.target.value)}/></label><label className="wide">Raison de la modification<input required value={reason} onChange={event=>setReason(event.target.value)}/></label><button className="button" disabled={!ready} onClick={save}>Enregistrer</button></div>}</section>;
}
