"use client";
import{useState}from"react";
import{useAuth}from"@/features/auth/AuthProvider";
import{canManageTrainingObjectives}from"@/features/auth/types";
import type{TrainingProgram,TrainingProgressMilestone}from"@/features/programs/types";
import{resolveTrainingObjectives}from"./calculations";
import{saveTrainingProgressObjective}from"./objectives";

export function StudentTrainingObjectivesPanel({studentId,studentName,cohortId,cohortName,program,objectives}:{studentId:string;studentName:string;cohortId:string;cohortName?:string;program:TrainingProgram;objectives:TrainingProgressMilestone[]}){
 const{profile}=useAuth(),canEdit=canManageTrainingObjectives(profile),[editing,setEditing]=useState(false),[baseId,setBaseId]=useState(""),[targetDate,setTargetDate]=useState(""),[notes,setNotes]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState("");
 const programObjectives=objectives.filter(item=>item.programId===program.id),cohortObjectives=programObjectives.filter(item=>item.scope==="cohort"&&item.cohortId===cohortId),applied=resolveTrainingObjectives(programObjectives,cohortId,studentId,cohortName),individual=programObjectives.filter(item=>item.scope==="student"&&item.studentId===studentId),base=cohortObjectives.find(item=>item.id===baseId),ready=Boolean(base&&targetDate&&reason.trim());
 function selectBase(id:string){const value=cohortObjectives.find(item=>item.id===id);setBaseId(id);setTargetDate(value?.targetDate||"");setNotes(value?.notes||"")}
 async function save(){if(!base||!ready)return;try{setError("");const now=new Date().toISOString(),actor=profile?.uid||"",existingOverride=individual.find(item=>item.phaseId===base.phaseId&&item.milestoneType===base.milestoneType&&item.title.trim().toLowerCase()===base.title.trim().toLowerCase()),id=existingOverride?.id||`objectif-etudiant-${studentId}-${Date.now()}`,value:TrainingProgressMilestone={...base,id,scope:"student",cohortId,studentId,targetDate,notes:notes.trim()||undefined,createdBy:existingOverride?.createdBy||actor,createdAt:existingOverride?.createdAt||now,updatedBy:actor,updatedAt:now};await saveTrainingProgressObjective(value,programObjectives,{author:actor,reason});setEditing(false);setBaseId("");setTargetDate("");setNotes("");setReason("")}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible")}}
 return <section className="card student-training-objectives"><header><div><h3>Objectifs de progression — {studentName}</h3><p className="muted">Cet objectif remplace seulement l’objectif de cohorte correspondant pour cet étudiant.</p></div>{canEdit&&cohortObjectives.length>0&&<button className="button secondary" onClick={()=>setEditing(value=>!value)}>+ Personnalisation étudiant</button>}</header>{error&&<div className="notice error">{error}</div>}{cohortName&&<p><span className="badge">Cohorte {cohortName}</span></p>}<div className="milestone-list">{applied.map(item=><article key={item.id}><div><span className="badge">{item.appliedSource}</span><strong>{item.title}</strong><small>{item.phaseId?`Phase ${item.phaseId}`:"Programme complet"}</small></div><p>{item.targetDate||"Aucune date cible"}</p></article>)}{!applied.length&&<p>Aucun objectif de cohorte applicable.</p>}</div>{individual.length>0&&<p className="muted">{individual.length} personnalisation(s) individuelle(s).</p>}{editing&&<div className="program-form-grid"><label className="wide">Objectif de cohorte à remplacer<select required value={baseId} onChange={event=>selectBase(event.target.value)}><option value="">Sélectionner</option>{cohortObjectives.map(item=><option key={item.id} value={item.id}>{item.title} · Phase {item.phaseId} · {item.targetDate}</option>)}</select></label><label>Étudiant<input value={studentName} readOnly/></label><label>Nouvelle date cible<input required type="date" value={targetDate} onChange={event=>setTargetDate(event.target.value)}/></label><label className="wide">Notes<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><label className="wide">Raison de la modification<input required value={reason} onChange={event=>setReason(event.target.value)} placeholder="Ex. formation à temps partiel"/></label><button className="button" disabled={!ready} onClick={save}>Enregistrer l’exception</button></div>}</section>;
}
