"use client";
import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import{PageHeader}from"@/components/ui/PageHeader";
import{useAuth}from"@/features/auth/AuthProvider";
import{canViewTrainingManagementDashboard}from"@/features/auth/types";
import{subscribeStudents,subscribeInstructors}from"@/features/students/firestore";
import type{Student,InstructorOption}from"@/features/students/types";
import{subscribeTrainingCohorts}from"@/features/training-cohorts/firestore";
import type{TrainingCohort}from"@/features/training-cohorts/types";
import{subscribeManagedPrograms,type ManagedTrainingProgram}from"@/features/programs/management";
import{subscribeTrainingProgressObjectives}from"./objectives";
import{compareTrainingPrograms,type TrainingProgressMilestone}from"@/features/programs/types";
import{OFFICIAL_PROGRAMS,VISIBLE_OFFICIAL_PROGRAMS}from"@/features/programs/modularPrograms";
import{activityHours,calculateProgress,resolveTrainingObjectives,plannedActivityHours}from"./calculations";
import{subscribeAllProgressActivities,subscribeAllProgressLessons}from"./firestore";
import type{ProgressActivity,ProgressLesson,ProgressStatus}from"./types";
import"./training-progress.css";

const statusOrder:Record<ProgressStatus,number>={Critique:0,"En retard":1,"À surveiller":2,"Non configuré":3,Conforme:4,"En avance":5};
const monday=(date:Date)=>{const value=new Date(date);value.setHours(0,0,0,0);value.setDate(value.getDate()-((value.getDay()+6)%7));return value};
const iso=(date:Date)=>date.toISOString().slice(0,10);
const fmtHours=(value:number)=>`${Math.round(value*10)/10} h`;
const pct=(value:number|null)=>value===null?"—":`${value} %`;

export function TrainingProgressDashboard(){
 const{profile}=useAuth(),[students,setStudents]=useState<Student[]>([]),[instructors,setInstructors]=useState<InstructorOption[]>([]),[cohorts,setCohorts]=useState<TrainingCohort[]>([]),[lessons,setLessons]=useState<ProgressLesson[]>([]),[activities,setActivities]=useState<ProgressActivity[]>([]),[trainingObjectives,setTrainingObjectives]=useState<TrainingProgressMilestone[]>([]),[managed,setManaged]=useState<ManagedTrainingProgram[]>([]),[error,setError]=useState("");
 const[cohort,setCohort]=useState(""),[instructor,setInstructor]=useState(""),[program,setProgram]=useState(""),[status,setStatus]=useState(""),[search,setSearch]=useState("");
 useEffect(()=>{const fail=(value:Error)=>setError(value.message);const off=[subscribeStudents({next:setStudents,error:fail}),subscribeInstructors({next:setInstructors,error:fail}),subscribeTrainingCohorts(setCohorts,fail),subscribeAllProgressLessons(setLessons,fail),subscribeAllProgressActivities(setActivities,fail),subscribeTrainingProgressObjectives(setTrainingObjectives,fail),subscribeManagedPrograms(setManaged,fail)];return()=>off.forEach(item=>item())},[]);
 // Les définitions complètes (y compris les modules historiques) restent disponibles
 // pour calculer la progression. Le filtre, lui, ne montre que les vrais programmes actifs.
 const programDefinitions=useMemo(()=>[...OFFICIAL_PROGRAMS,...managed.filter(item=>!OFFICIAL_PROGRAMS.some(official=>official.id===item.id))],[managed]);
 const programs=useMemo(()=>[...new Map([...VISIBLE_OFFICIAL_PROGRAMS,...managed.filter(item=>item.catalogKind==="program"&&item.status!=="inactive")].map(item=>[item.id,item])).values()].sort(compareTrainingPrograms),[managed]);
 const week=useMemo(()=>{const start=monday(new Date()),end=new Date(start);end.setDate(end.getDate()+6);return{start:iso(start),end:iso(end)}},[]);
 const rows=useMemo(()=>students.filter(item=>item.status==="Actif").map(student=>{const trainingCohort=cohorts.find(item=>item.studentIds.includes(student.id)),programId=trainingCohort?.programId||student.trainingProgramId||student.program,studentActivities=activities.filter(item=>item.studentId===student.id||item.participantStudentIds.includes(student.id)),cohortName=trainingCohort?.name||"",milestones=resolveTrainingObjectives(trainingObjectives.filter(item=>item.programId===programId),trainingCohort?.id||"",student.id,cohortName),programDefinition=programDefinitions.find(item=>item.id===programId),progress=calculateProgress({studentId:student.id,startDate:trainingCohort?.startDate||student.startDate,program:programDefinition,lessons,activities,milestones}),weekActivities=studentActivities.filter(item=>item.date>=week.start&&item.date<=week.end),future=studentActivities.filter(item=>item.date>week.end&&item.status!=="Annulé").length;return{student,trainingCohortId:trainingCohort?.id||"",name:`${student.firstName} ${student.lastName}`.trim(),programId,programName:programDefinition?.name||student.trainingProgramName||student.program,cohortName:cohortName||"Sans cohorte",instructorName:instructors.find(item=>item.id===student.primaryInstructorId)?.name||"Non assigné",progress,weekPlanned:weekActivities.reduce((sum,item)=>sum+plannedActivityHours(item),0),weekActual:weekActivities.reduce((sum,item)=>sum+activityHours(item),0),future}}),[students,activities,trainingObjectives,programDefinitions,lessons,week,cohorts,instructors]);
 const filtered=useMemo(()=>rows.filter(row=>(!cohort||row.trainingCohortId===cohort)&&(!instructor||row.student.primaryInstructorId===instructor)&&(!program||row.programId===program)&&(!status||row.progress.status.status===status)&&(!search||row.name.toLowerCase().includes(search.toLowerCase()))),[rows,cohort,instructor,program,status,search]);
 const metrics=useMemo(()=>{const normal=filtered.filter(row=>["En avance","Conforme"].includes(row.progress.status.status)).length,configured=filtered.filter(row=>row.progress.expectedPercent!==null),mean=configured.length?Math.round(configured.reduce((sum,row)=>sum+row.progress.actualPercent,0)/configured.length):null;return{normal,watch:filtered.filter(row=>row.progress.status.status==="À surveiller").length,late:filtered.filter(row=>row.progress.status.status==="En retard").length,critical:filtered.filter(row=>row.progress.status.status==="Critique").length,mean,planned:filtered.reduce((sum,row)=>sum+row.weekPlanned,0),actual:filtered.reduce((sum,row)=>sum+row.weekActual,0),inactive:filtered.filter(row=>(row.progress.daysInactive??0)>=7).length}},[filtered]);
 const interventions=filtered.filter(row=>["Critique","En retard","À surveiller"].includes(row.progress.status.status)).sort((a,b)=>statusOrder[a.progress.status.status]-statusOrder[b.progress.status.status]);
 if(!canViewTrainingManagementDashboard(profile))return <section className="card access-denied"><h1>Accès refusé</h1><p>Ce tableau de gestion est actuellement réservé à la Direction et au Chef instructeur.</p></section>;
 return <div className="progress-dashboard"><PageHeader title="Suivi de progression" subtitle="Vue de gestion fondée sur les dossiers étudiants, le PTR, les activités et les objectifs de cohorte."/>{error&&<div className="error-banner">{error}</div>}
  <section className="progress-filters card"><label>Cohorte<select value={cohort} onChange={e=>setCohort(e.target.value)}><option value="">Toutes</option>{cohorts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Instructeur<select value={instructor} onChange={e=>setInstructor(e.target.value)}><option value="">Tous</option>{instructors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Programme<select value={program} onChange={e=>setProgram(e.target.value)}><option value="">Tous</option>{programs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Statut<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous</option>{["En avance","Conforme","À surveiller","En retard","Critique","Non configuré"].map(x=><option key={x}>{x}</option>)}</select></label><label>Étudiant<input placeholder="Rechercher…" value={search} onChange={e=>setSearch(e.target.value)}/></label></section>
  <section className="progress-kpis">{[["Étudiants actifs",filtered.length],["Progression normale",metrics.normal],["À surveiller",metrics.watch],["En retard",metrics.late],["Critiques",metrics.critical],["Progression moyenne",pct(metrics.mean)],["Heures prévues semaine",fmtHours(metrics.planned)],["Heures réalisées semaine",fmtHours(metrics.actual)],["Sans activité récente",metrics.inactive]].map(([label,value])=><article className="card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
  {interventions.length>0&&<section className="card intervention"><h2>Étudiants nécessitant une intervention</h2><div className="intervention-grid">{interventions.slice(0,6).map(row=><article key={row.student.id}><span className={`progress-badge status-${row.progress.status.status.toLowerCase().replaceAll(" ","-")}`}>{row.progress.status.status}</span><strong>{row.name} — {row.programName}</strong><small>{row.instructorName}</small><p>{row.progress.status.reason}</p><b>Action : {row.progress.status.action}</b></article>)}</div></section>}
  <section className="card progress-table-card"><div className="section-heading"><div><h2>Progression des étudiants</h2><p>{filtered.length} dossier{filtered.length===1?"":"s"} affiché{filtered.length===1?"":"s"}</p></div></div><div className="progress-table-wrap"><table><thead><tr><th>Étudiant</th><th>Programme</th><th>Phase actuelle</th><th>Instructeur</th><th>Réelle</th><th>Attendue</th><th>Écart</th><th>Heures prévues</th><th>Heures réalisées</th><th>Leçons</th><th>Dernière activité</th><th>Prochaine échéance</th><th>Statut</th><th>Accès</th></tr></thead><tbody>{filtered.map(row=><tr key={row.student.id}><td><Link href={`/students/${row.student.id}`}>{row.name}</Link><small>{row.cohortName}</small></td><td>{row.programName}</td><td>Phase {row.progress.currentPhaseId}<small>{row.progress.currentPhaseName}</small></td><td>{row.instructorName}</td><td><div className="mini-progress"><i style={{width:`${row.progress.actualPercent}%`}}/></div>{pct(row.progress.actualPercent)}</td><td>{pct(row.progress.expectedPercent)}</td><td>{row.progress.gap===null?"—":`${row.progress.gap>0?"+":""}${row.progress.gap} %`}</td><td>{fmtHours(row.progress.plannedHours)}<small>Vol {fmtHours(row.progress.plannedFlightHours)} · Sol {fmtHours(row.progress.plannedGroundHours)} · Sim {fmtHours(row.progress.plannedSimulatorHours)}</small></td><td>{fmtHours(row.progress.realizedHours)}</td><td>{row.progress.completedPhaseLessons} / {row.progress.plannedLessons}</td><td>{row.progress.lastActivity||"Aucune"}<small>{row.progress.daysInactive===null?"":` (${row.progress.daysInactive} j)`}</small></td><td>{row.progress.nextMilestone?<>{row.progress.nextMilestone.title}<small>{row.progress.nextMilestone.targetDate}</small></>:"Aucune"}</td><td><span className={`progress-badge status-${row.progress.status.status.toLowerCase().replaceAll(" ","-")}`}>{row.progress.status.status}</span><small>{row.progress.status.reason}</small></td><td className="row-actions"><Link href={`/students/${row.student.id}`}>Dossier</Link><Link href={`/ptr/${row.student.id}`}>PTR</Link><Link href={`/schedule?studentId=${row.student.id}`}>Horaire</Link></td></tr>)}</tbody></table></div></section>
  <section className="progress-summary-grid"><article className="card"><h2>Résumé de la sélection</h2><p><strong>{filtered.length}</strong> étudiants · <strong>{pct(metrics.mean)}</strong> de progression moyenne</p><p><strong>{metrics.late+metrics.critical}</strong> en retard ou critiques · <strong>{fmtHours(metrics.actual)}</strong> réalisées cette semaine</p>{instructor&&<p><strong>{filtered.reduce((sum,row)=>sum+row.future,0)}</strong> activités futures planifiées pour les étudiants de cet instructeur.</p>}</article><article className="card"><h2>Source des objectifs</h2><p>Les objectifs communs sont configurés dans <Link href="/training-cohorts"><strong>Cohortes</strong></Link>. Une personnalisation étudiant remplace uniquement l’objectif correspondant.</p></article></section>
 </div>
}
