import{addDoc,collection,doc,onSnapshot,serverTimestamp,setDoc,updateDoc,type DocumentData,type FirestoreError,type Unsubscribe}from"firebase/firestore";
import{db}from"@/services/firebase/client";
import type{TrainingQuote,TrainingRate,TrainingTaxSettings}from"./types";
type Handlers<T>={next:(items:T[])=>void;error:(error:FirestoreError)=>void};
const text=(v:unknown)=>typeof v==="string"?v:"",number=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:Number(v)||0;
const withoutUndefined=(value:unknown):unknown=>Array.isArray(value)?value.map(withoutUndefined):value&&typeof value==="object"&&Object.getPrototypeOf(value)===Object.prototype?Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined).map(([key,item])=>[key,withoutUndefined(item)])):value;
const mapRate=(id:string,d:DocumentData):TrainingRate=>({id,name:text(d.name),category:d.category,description:text(d.description),price:number(d.price),unit:d.unit,taxable:d.taxable===true,active:d.active!==false,effectiveDate:text(d.effectiveDate),aircraftId:text(d.aircraftId)||undefined,aircraftType:text(d.aircraftType)||undefined,t2202Eligible:d.t2202Eligible===true,tp752Eligible:d.tp752Eligible===true,createdAt:d.createdAt,updatedAt:d.updatedAt});
const mapQuote=(id:string,d:DocumentData):TrainingQuote=>({id,quoteNumber:text(d.quoteNumber),date:text(d.date),expirationDate:text(d.expirationDate),customerType:d.customerType==="student"?"student":"prospect",studentId:text(d.studentId)||undefined,customerName:text(d.customerName),customerPhone:text(d.customerPhone),customerEmail:text(d.customerEmail),trainingType:text(d.trainingType),notes:text(d.notes),status:d.status,lines:Array.isArray(d.lines)?d.lines:[],subtotal:number(d.subtotal),gstRate:typeof d.gstRate==="number"?d.gstRate:5,qstRate:typeof d.qstRate==="number"?d.qstRate:9.975,gst:number(d.gst),qst:number(d.qst),taxes:number(d.taxes),total:number(d.total),templateId:text(d.templateId)||undefined,createdBy:text(d.createdBy),createdAt:d.createdAt,updatedAt:d.updatedAt});
export function subscribeTrainingRates(h:Handlers<TrainingRate>):Unsubscribe{return onSnapshot(collection(db,"trainingRates"),s=>h.next(s.docs.map(x=>mapRate(x.id,x.data())).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name))),h.error)}
export function subscribeTrainingQuotes(h:Handlers<TrainingQuote>):Unsubscribe{return onSnapshot(collection(db,"trainingQuotes"),s=>h.next(s.docs.map(x=>mapQuote(x.id,x.data())).sort((a,b)=>b.date.localeCompare(a.date)||b.quoteNumber.localeCompare(a.quoteNumber))),h.error)}
export function subscribeTrainingTaxSettings(next:(value:TrainingTaxSettings)=>void,error:(error:FirestoreError)=>void):Unsubscribe{return onSnapshot(doc(db,"trainingQuoteSettings","taxes"),s=>{const d=s.data();next({gstRate:typeof d?.gstRate==="number"?d.gstRate:5,qstRate:typeof d?.qstRate==="number"?d.qstRate:9.975,updatedAt:d?.updatedAt})},error)}
export async function saveTrainingTaxSettings(settings:TrainingTaxSettings){await setDoc(doc(db,"trainingQuoteSettings","taxes"),{gstRate:Number(settings.gstRate),qstRate:Number(settings.qstRate),updatedAt:serverTimestamp()},{merge:true})}
export async function saveTrainingRate(rate:TrainingRate){const{id,...data}=rate,ref=id?doc(db,"trainingRates",id):doc(collection(db,"trainingRates"));await setDoc(ref,{...withoutUndefined(data) as Record<string,unknown>,updatedAt:serverTimestamp(),...(!id?{createdAt:serverTimestamp()}: {})},{merge:true});return ref.id}
export async function setTrainingRateActive(id:string,active:boolean){await updateDoc(doc(db,"trainingRates",id),{active,updatedAt:serverTimestamp()})}
export async function saveTrainingQuote(quote:TrainingQuote){const{id,...data}=quote,payload=withoutUndefined(data) as Record<string,unknown>;if(id){await setDoc(doc(db,"trainingQuotes",id),{...payload,updatedAt:serverTimestamp()},{merge:true});return id}const ref=await addDoc(collection(db,"trainingQuotes"),{...payload,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return ref.id}
