"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "@/components/ui/PageHeader";
import { addHistory, addStudentDocument, addStudentNote, deleteStudentDocument, deleteStudentNote, removeStudent, saveStudent, subscribeDocuments, subscribeHistory, subscribeInstructors, subscribeLessons, subscribeNotes, subscribeReservations, subscribeStudent } from "./firestore";
import { expiryStatus, initials, progressPercent } from "./utils";
import type { InstructorOption, Student, StudentDocument, StudentDocumentType, StudentHistoryItem, StudentLesson, StudentNote, StudentReservation, StudentProgram } from "./types";
import { programTypeFor, STUDENT_PROGRAMS } from "./programs";
const tabs=["Résumé","Informations","Documents","Progression","Réservations","Notes","Historique"] as const; type Tab=typeof tabs[number];
export function StudentDetailPage({studentId}:{studentId:string}){
 const router=useRouter(); const [student,setStudent]=useState<Student|null>(null); const [instructors,setInstructors]=useState<InstructorOption[]>([]); const [docs,setDocs]=useState<StudentDocument[]>([]); const [notes,setNotes]=useState<StudentNote[]>([]); const [history,setHistory]=useState<StudentHistoryItem[]>([]); const [lessons,setLessons]=useState<StudentLesson[]>([]); const [reservations,setReservations]=useState<StudentReservation[]>([]); const [tab,setTab]=useState<Tab>("Résumé"); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [noteText,setNoteText]=useState("");
 const [docForm,setDocForm]=useState({type:"Certificat médical" as StudentDocumentType,number:"",issueDate:"",expiryDate:"",notes:""});
 useEffect(()=>{const errs=(e:Error)=>setError(e.message);const u=[subscribeStudent(studentId,x=>{setStudent(x);setLoading(false)},errs),subscribeInstructors({next:setInstructors,error:errs}),subscribeDocuments(studentId,{next:setDocs,error:errs}),subscribeNotes(studentId,{next:setNotes,error:errs}),subscribeHistory(studentId,{next:setHistory,error:errs}),subscribeLessons(studentId,{next:setLessons,error:errs}),subscribeReservations(studentId,{next:setReservations,error:errs})];return()=>u.forEach(x=>x())},[studentId]);
 const instructor=instructors.find(i=>i.id===student?.primaryInstructorId); const progress=progressPercent(lessons); const upcoming=useMemo(()=>reservations.filter(r=>r.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>a.date.localeCompare(b.date)),[reservations]);
 async function save(){if(!student)return;try{await saveStudent(student,true);await addHistory({studentId,type:"Modification",title:"Dossier mis à jour",detail:"Informations générales modifiées"});setMessage("Dossier enregistré.")}catch(e){setError(e instanceof Error?e.message:"Erreur")}}
 async function addDoc(e:React.FormEvent){e.preventDefault();const status=expiryStatus(docForm.expiryDate);await addStudentDocument({...docForm,studentId,status});await addHistory({studentId,type:"Document",title:`Document ajouté : ${docForm.type}`,detail:status});setDocForm({type:"Certificat médical",number:"",issueDate:"",expiryDate:"",notes:""});setMessage("Document ajouté.")}
 async function addNote(e:React.FormEvent){e.preventDefault();if(!noteText.trim())return;await addStudentNote({studentId,text:noteText.trim(),author:"Équipe Orizon"});await addHistory({studentId,type:"Note",title:"Note ajoutée",detail:noteText.trim().slice(0,120)});setNoteText("")}
 if(loading)return <><a className="button" href={`/ptr/${studentId}`} style={{ marginBottom: 16 }}>Ouvrir le PTR électronique</a>
      <PageHeader title="Dossier étudiant" subtitle="Chargement…"/><section className="card">Chargement du dossier…</section></>; if(!student)return <><PageHeader title="Dossier étudiant" subtitle="Introuvable"/><section className="card">Cet étudiant n’existe pas.</section></>;
 return <><PageHeader title={`${student.firstName} ${student.lastName}`} subtitle={`${student.program} · ${student.programType} · ${student.status}`}/>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
 <section className="student-profile-head"><div className="student-avatar large">{initials(student.firstName,student.lastName)}</div><div><strong>{student.firstName} {student.lastName}</strong><span>{student.email||"Aucun courriel"}</span><span>Instructeur principal : {instructor?.name||"Non assigné"}</span></div><div className="profile-metrics"><div><b>{student.flightHours.toFixed(1)}</b><span>Heures vol</span></div><div><b>{student.groundHours.toFixed(1)}</b><span>Heures sol</span></div><div><b>{progress}%</b><span>Progression</span></div></div></section>
 <div className="student-tabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==="Résumé"&&<div className="student-summary-grid"><section className="card"><h3>Progression</h3><div className="progress-bar"><span style={{width:`${progress}%`}}/></div><p>{lessons.filter(x=>x.status==="Réussi").length} leçon(s) réussie(s) sur {lessons.length}</p><button className="button secondary" onClick={()=>setTab("Progression")}>Voir le PTR</button></section><section className="card"><h3>Prochaine réservation</h3>{upcoming[0]?<><b>{upcoming[0].date} · {upcoming[0].startTime}-{upcoming[0].endTime}</b><p>{upcoming[0].type} · {upcoming[0].title}</p></>:<p>Aucune réservation à venir.</p>}<button className="button secondary" onClick={()=>setTab("Réservations")}>Toutes les réservations</button></section><section className="card"><h3>Documents à surveiller</h3>{docs.filter(x=>x.status!=="Valide"&&x.status!=="Sans expiration").slice(0,4).map(x=><div className={`document-mini ${x.status==='Expiré'?'bad':'warn'}`} key={x.id}><b>{x.type}</b><span>{x.status}</span></div>)}{!docs.some(x=>x.status!=="Valide"&&x.status!=="Sans expiration")&&<p>Aucune alerte.</p>}</section><section className="card"><h3>Dernières notes</h3>{notes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3).map(n=><p key={n.id}>{n.text}</p>)}{!notes.length&&<p>Aucune note.</p>}</section></div>}
 {tab==="Informations"&&<section className="card student-form"><div className="form-grid"><label>Prénom<input value={student.firstName} onChange={e=>setStudent({...student,firstName:e.target.value})}/></label><label>Nom<input value={student.lastName} onChange={e=>setStudent({...student,lastName:e.target.value})}/></label><label>Courriel<input value={student.email} onChange={e=>setStudent({...student,email:e.target.value})}/></label><label>Téléphone<input value={student.phone} onChange={e=>setStudent({...student,phone:e.target.value})}/></label><label>Programme<select value={student.program} onChange={e=>{const program=e.target.value as StudentProgram;setStudent({...student,program,programType:programTypeFor(program)})}}>{STUDENT_PROGRAMS.map(program=><option key={program}>{program}</option>)}</select></label><label>Type<input value={student.programType} readOnly /></label><label>Statut<select value={student.status} onChange={e=>setStudent({...student,status:e.target.value as Student["status"]})}><option>Actif</option><option>En pause</option><option>Diplômé</option><option>Retiré</option></select></label><label>Langue<select value={student.language} onChange={e=>setStudent({...student,language:e.target.value as Student["language"]})}><option>Français</option><option>Anglais</option></select></label><label>Instructeur principal<select value={student.primaryInstructorId} onChange={e=>setStudent({...student,primaryInstructorId:e.target.value})}><option value="">Non assigné</option>{instructors.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Date début<input type="date" value={student.startDate} onChange={e=>setStudent({...student,startDate:e.target.value})}/></label><label>Heures vol<input type="number" step="0.1" value={student.flightHours} onChange={e=>setStudent({...student,flightHours:Number(e.target.value)})}/></label><label>Heures sol<input type="number" step="0.1" value={student.groundHours} onChange={e=>setStudent({...student,groundHours:Number(e.target.value)})}/></label></div><label>Adresse<textarea value={student.address} onChange={e=>setStudent({...student,address:e.target.value})}/></label><div className="form-grid"><label>Contact urgence<input value={student.emergencyContact} onChange={e=>setStudent({...student,emergencyContact:e.target.value})}/></label><label>Téléphone urgence<input value={student.emergencyPhone} onChange={e=>setStudent({...student,emergencyPhone:e.target.value})}/></label></div><div className="form-actions"><button className="button danger" onClick={async()=>{if(confirm("Supprimer définitivement ce dossier?")){await removeStudent(studentId);router.push('/students')}}}>Supprimer</button><button className="button" onClick={save}>Enregistrer</button></div></section>}
 {tab==="Documents"&&<div className="two-column"><section className="card"><h3>Documents</h3><div className="document-list">{docs.map(d=><div className={`document-row ${d.status==='Expiré'?'bad':d.status==='À surveiller'?'warn':''}`} key={d.id}><div><b>{d.type}</b><span>No {d.number||"—"} · Exp. {d.expiryDate||"—"}</span></div><span>{d.status}</span><button className="icon-button" onClick={()=>deleteStudentDocument(d.id)}>×</button></div>)}{!docs.length&&<p>Aucun document.</p>}</div></section><form className="card student-form" onSubmit={addDoc}><h3>Ajouter un document</h3><label>Type<select value={docForm.type} onChange={e=>setDocForm({...docForm,type:e.target.value as StudentDocumentType})}>{["Certificat médical","Passeport","Certificat de naissance","Permis d’élève-pilote","Licence","Certificat radio","Photo","Document immigration","Autre"].map(x=><option key={x}>{x}</option>)}</select></label><label>Numéro<input value={docForm.number} onChange={e=>setDocForm({...docForm,number:e.target.value})}/></label><div className="form-grid"><label>Émission<input type="date" value={docForm.issueDate} onChange={e=>setDocForm({...docForm,issueDate:e.target.value})}/></label><label>Expiration<input type="date" value={docForm.expiryDate} onChange={e=>setDocForm({...docForm,expiryDate:e.target.value})}/></label></div><label>Notes<textarea value={docForm.notes} onChange={e=>setDocForm({...docForm,notes:e.target.value})}/></label><button className="button">Ajouter</button></form></div>}
 {tab==="Progression"&&<section className="card"><h3>Progression PTR</h3><div className="progress-bar"><span style={{width:`${progress}%`}}/></div><div className="lesson-list">{lessons.slice().sort((a,b)=>a.lessonNumber.localeCompare(b.lessonNumber,undefined,{numeric:true})).map(l=><div className="lesson-row" key={l.id}><span>{l.phase}</span><b>Leçon {l.lessonNumber} · {l.title}</b><span className={`status-badge ${l.status.toLowerCase().replaceAll(' ','-')}`}>{l.status}</span>{l.score&&<strong>TC {l.score}</strong>}</div>)}{!lessons.length&&<p>Aucune leçon PTR. Le module PTR complet alimentera cette section.</p>}</div></section>}
 {tab==="Réservations"&&<section className="card"><h3>Réservations</h3><div className="reservation-list">{reservations.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=><div className="reservation-row" key={r.id}><div><b>{r.date} · {r.startTime}-{r.endTime}</b><span>{r.type} · {r.title}</span></div><span className="status-badge">{r.status}</span></div>)}{!reservations.length&&<p>Aucune réservation liée.</p>}</div></section>}
 {tab==="Notes"&&<div className="two-column"><form className="card student-form" onSubmit={addNote}><h3>Ajouter une note</h3><textarea required value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Observation pédagogique ou administrative…"/><button className="button">Ajouter</button></form><section className="card"><h3>Notes</h3>{notes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(n=><div className="note-row" key={n.id}><div><b>{n.author}</b><span>{n.createdAt?new Date(n.createdAt).toLocaleString('fr-CA'):''}</span><p>{n.text}</p></div><button className="icon-button" onClick={()=>deleteStudentNote(n.id)}>×</button></div>)}{!notes.length&&<p>Aucune note.</p>}</section></div>}
 {tab==="Historique"&&<section className="card"><h3>Historique du dossier</h3><div className="timeline">{history.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(h=><div className="timeline-item" key={h.id}><span>{h.createdAt?new Date(h.createdAt).toLocaleString('fr-CA'):''}</span><b>{h.title}</b><p>{h.detail}</p></div>)}{!history.length&&<p>Aucun événement d’historique.</p>}</div></section>}
 </>;
}
