"use client";
import {useEffect,useMemo,useState} from "react";
import {PinSignaturePad} from "@/components/ui/PinSignaturePad";
import {useAuth} from "@/features/auth/AuthProvider";
import type {Student} from "./types";
import {MODULAR_TRACKS,programAgreementFor,signProgramAgreement,subscribeProgramAgreement,type StudentProgramAgreement} from "./programAgreements";

export function StudentProgramAgreementPanel({student}:{student:Student}){
 const{user,profile}=useAuth(),[modularTracks,setModularTracks]=useState<string[]>([]),definition=useMemo(()=>programAgreementFor(student,modularTracks.join(" · ")),[student,modularTracks]);
 const[agreement,setAgreement]=useState<StudentProgramAgreement|null>(null),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[form,setForm]=useState({candidateName:`${student.firstName} ${student.lastName}`.trim(),candidateLicense:"",accepted:false,candidateSignature:""});
 useEffect(()=>subscribeProgramAgreement(student.id,definition.key,setAgreement,value=>setError(value.message)),[student.id,definition.key]);
 const ready=Boolean(definition.track&&form.candidateName.trim()&&form.accepted&&form.candidateSignature);
 async function save(){if(!user||!profile||!ready)return;try{const signedAt=new Date().toISOString();await signProgramAgreement({studentId:student.id,studentProgram:student.program,programTrack:definition.track,documentKey:definition.key,documentTitle:definition.title,documentVersion:definition.version,documentSha256:definition.sha256,...form,signedAt,signedByUid:user.uid,signedByEmail:profile.email});setMessage("Programme d’entraînement signé. La preuve est maintenant conservée au PTR.")}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible.")}}
 if(agreement&&agreement.studentProgram===student.program)return <section className="card agreement-status signed"><div><span className="badge ok">Programme signé et valide</span><h3>{agreement.programTrack}</h3><p>{agreement.documentTitle} · version {agreement.documentVersion}</p><p>Signé par {agreement.candidateName} le {new Date(agreement.signedAt).toLocaleString("fr-CA",{dateStyle:"long",timeStyle:"short"})}</p><small>Preuve numérique : {agreement.documentSha256}</small></div><a className="button secondary" href={definition.pdfPath} target="_blank" rel="noreferrer">Consulter le programme officiel</a></section>;
 const toggleTrack=(track:string)=>setModularTracks(current=>current.includes(track)?current.filter(item=>item!==track):[...current,track]);
 return <section className="card agreement-panel"><div className="agreement-heading"><div><span className="badge warn">Signature obligatoire avant tout vol</span><h2>{definition.title}</h2><p>Document officiel de {definition.pageCount} pages · version {definition.version}</p></div><a className="button secondary" href={definition.pdfPath} target="_blank" rel="noreferrer">Ouvrir dans une nouvelle fenêtre</a></div>{student.program==="Modulaire"?<fieldset><legend>Choix de mes formations - cochez toutes les formations concernées</legend><div className="employee-role-grid">{MODULAR_TRACKS.map(track=><label key={track}><input type="checkbox" checked={modularTracks.includes(track)} onChange={()=>toggleTrack(track)}/>{track}</label>)}</div></fieldset>:<div className="notice"><b>Formation associée au dossier :</b> {definition.track}</div>}{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}<iframe className="agreement-pdf" title={definition.title} src={`${definition.pdfPath}#view=FitH`}/><div className="agreement-form"><h3>Signature et confirmation</h3><p>J’atteste avoir lu et compris l’ensemble des programmes d’entraînement en vol qui s’appliquent à ma formation désirée. J’ai reçu un exemplaire à jour des normes de test en vol et le guide d’étude applicable.</p><div className="form-grid"><label>Nom du candidat<input value={form.candidateName} onChange={event=>setForm({...form,candidateName:event.target.value})}/></label><label>Licence du candidat, si applicable<input value={form.candidateLicense} onChange={event=>setForm({...form,candidateLicense:event.target.value})}/></label></div><label className="agreement-check"><input type="checkbox" checked={form.accepted} onChange={event=>setForm({...form,accepted:event.target.checked})}/><span>Je confirme avoir sélectionné la ou les formations « {definition.track||"à déterminer"} », avoir lu le document et accepter les programmes applicables.</span></label><PinSignaturePad label="Signature électronique du candidat" studentId={student.id} signerName={form.candidateName||`${student.firstName} ${student.lastName}`} value={form.candidateSignature} onChange={value=>setForm({...form,candidateSignature:value})}/><div className="notice">Une fois signé, ce document devient une preuve permanente et ne peut plus être modifié.</div><button className="button" disabled={!ready} onClick={save}>Signer définitivement le programme d’entraînement</button></div></section>;
}
