"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "@/components/ui/PageHeader";
import { addHistory, saveStudent, subscribeInstructors } from "./firestore";
import type { InstructorOption, Student } from "./types";
const empty:Student={id:"",firstName:"",lastName:"",email:"",phone:"",address:"",emergencyContact:"",emergencyPhone:"",program:"PPL",programType:"Intégré",language:"Français",status:"Actif",primaryInstructorId:"",startDate:"",flightHours:0,groundHours:0,notes:""};
export function StudentEditorPage({mode}:{mode:"new"}){
 const router=useRouter(); const [form,setForm]=useState(empty); const [instructors,setInstructors]=useState<InstructorOption[]>([]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>subscribeInstructors({next:setInstructors,error:e=>setError(e.message)}),[]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const id=`student-${Date.now()}`;const student={...form,id};await saveStudent(student,false);await addHistory({studentId:id,type:"Création",title:"Dossier créé",detail:`Programme ${student.program} (${student.programType})`});router.push(`/students/${id}`)}catch(err){setError(err instanceof Error?err.message:"Erreur") }finally{setSaving(false)}}
 return <><PageHeader title="Ajouter un étudiant" subtitle="Création du dossier de formation" />{error&&<div className="notice error">{error}</div>}<form className="card student-form" onSubmit={submit}><div className="form-grid"><label>Prénom<input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>Nom<input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label>Courriel<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Programme<input value={form.program} onChange={e=>setForm({...form,program:e.target.value})}/></label><label>Type<select value={form.programType} onChange={e=>setForm({...form,programType:e.target.value as Student["programType"]})}><option>Intégré</option><option>Modulaire</option></select></label><label>Instructeur principal<select value={form.primaryInstructorId} onChange={e=>setForm({...form,primaryInstructorId:e.target.value})}><option value="">Non assigné</option>{instructors.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Date de début<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Langue<select value={form.language} onChange={e=>setForm({...form,language:e.target.value as Student["language"]})}><option>Français</option><option>Anglais</option></select></label><label>Statut<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Student["status"]})}><option>Actif</option><option>En pause</option><option>Diplômé</option><option>Retiré</option></select></label></div><label>Adresse<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><div className="form-grid"><label>Contact d’urgence<input value={form.emergencyContact} onChange={e=>setForm({...form,emergencyContact:e.target.value})}/></label><label>Téléphone urgence<input value={form.emergencyPhone} onChange={e=>setForm({...form,emergencyPhone:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="button secondary" onClick={()=>router.push('/students')}>Annuler</button><button className="button" disabled={saving}>{saving?"Enregistrement…":"Créer le dossier"}</button></div></form></>;
}
