"use client";
import { useEffect,useState } from "react";
import { createUserWithEmailAndPassword,isSignInWithEmailLink,sendPasswordResetEmail,signInWithEmailAndPassword,signInWithEmailLink,updateProfile } from "firebase/auth";
import { auth } from "@/services/firebase/client";
import { OrizonLogo } from "@/components/branding/OrizonLogo";

export function LoginPage(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[initial,setInitial]=useState(false),[inviteLink,setInviteLink]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const isTest=process.env.NEXT_PUBLIC_APP_ENV==="test";
 useEffect(()=>setInviteLink(isSignInWithEmailLink(auth,window.location.href)),[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{if(inviteLink){await signInWithEmailLink(auth,email.trim().toLowerCase(),window.location.href);}else if(initial&&!isTest){const result=await createUserWithEmailAndPassword(auth,email,password);if(name.trim())await updateProfile(result.user,{displayName:name.trim()});}else await signInWithEmailAndPassword(auth,email,password);}catch(error){setMessage(error instanceof Error?error.message:"Connexion impossible.");}finally{setBusy(false)}}
 async function reset(){if(!email){setMessage("Inscrivez votre courriel avant de demander un nouveau mot de passe.");return;}try{await sendPasswordResetEmail(auth,email);setMessage("Un courriel de réinitialisation a été envoyé.");}catch(error){setMessage(error instanceof Error?error.message:"Envoi impossible.");}}
 return <main className="login-page"><section className="login-card"><div className="login-brand"><OrizonLogo/></div><h1>{inviteLink?"Accepter l’invitation":initial?"Créer l’administrateur initial":"Connexion"}</h1><p>{inviteLink?"Confirmez l’adresse qui a reçu cette invitation.":initial?"À utiliser uniquement lors de la première configuration.":"Connectez-vous pour accéder aux opérations."}</p>{message&&<div className={`notice ${message.includes("envoyé")?"":"error"}`}>{message}</div>}<form onSubmit={submit}>{initial&&!inviteLink&&<label>Nom complet<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Adresse courriel<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{!inviteLink&&<label>Mot de passe<input type="password" autoComplete={initial?"new-password":"current-password"} minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="button" disabled={busy}>{busy?"Veuillez patienter…":inviteLink?"Continuer et choisir mon mot de passe":initial?"Créer le compte":"Se connecter"}</button></form>{!initial&&!inviteLink&&<button className="text-button" onClick={reset}>Mot de passe oublié?</button>}{!isTest&&!inviteLink&&<button className="text-button setup" onClick={()=>{setInitial(!initial);setMessage("")}}>{initial?"Retour à la connexion":"Première configuration"}</button>}</section></main>}
