"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import{PageHeader}from"@/components/ui/PageHeader";
import{subscribeReservations,subscribeResources,subscribeStudents,type StudentOption}from"@/features/scheduler/firestore";
import type{SchedulerEvent,SchedulerResource}from"@/features/scheduler/types";
import{deleteTheoryCohort,deleteTheorySession,saveTheoryCohort,saveTheorySession,subscribeTheoryCohorts,subscribeTheorySessions}from"./firestore";
import type{TheoryCohort,TheorySession}from"./types";
import{OFFICIAL_PROGRAMS}from"@/features/programs/modularPrograms";
import{subscribeManagedPrograms,type ManagedTrainingProgram}from"@/features/programs/management";
import{subscribeTrainingProgressObjectives}from"@/features/training-progress/objectives";
import type{TrainingProgressMilestone}from"@/features/programs/types";
import{CohortTrainingObjectivesPanel}from"@/features/training-progress/CohortTrainingObjectivesPanel";

const today=()=>new Date().toISOString().slice(0,10);
const minutes=(value:string)=>{const[hour,minute]=value.split(":").map(Number);return hour*60+minute;};
const eventStudents=(event:SchedulerEvent)=>[event.studentId,...(event.participantStudentIds||[])].filter((id):id is string=>Boolean(id));
export function TheoryPage(){
  const[students,setStudents]=useState<StudentOption[]>([]),[resources,setResources]=useState<SchedulerResource[]>([]),[events,setEvents]=useState<SchedulerEvent[]>([]),[cohorts,setCohorts]=useState<TheoryCohort[]>([]),[sessions,setSessions]=useState<TheorySession[]>([]),[managedPrograms,setManagedPrograms]=useState<ManagedTrainingProgram[]>([]),[trainingObjectives,setTrainingObjectives]=useState<TrainingProgressMilestone[]>([]);
  const[message,setMessage]=useState(""),[error,setError]=useState("");
  const[attendanceSession,setAttendanceSession]=useState<TheorySession|null>(null);
  const[editingSessionId,setEditingSessionId]=useState("");
  const requestedSessionHandled=useRef(false);
  const[attendanceForm,setAttendanceForm]=useState<Record<string,"Présent"|"Absent">>({});
  const[cohort,setCohort]=useState<TheoryCohort>({id:"",name:"",program:"",studentIds:[]});
  const[session,setSession]=useState({title:"",program:"",topic:"",date:today(),startTime:"09:00",endTime:"12:00",instructorId:"",roomId:"",cohortId:"",studentIds:[] as string[],notes:""});
  useEffect(()=>{const fail=(value:Error)=>setError(value.message);const a=subscribeStudents({next:setStudents,error:fail}),b=subscribeResources({next:setResources,error:fail}),c=subscribeReservations({next:setEvents,error:fail}),d=subscribeTheoryCohorts(setCohorts,fail),e=subscribeTheorySessions(setSessions,fail),f=subscribeManagedPrograms(setManagedPrograms,fail),g=subscribeTrainingProgressObjectives(setTrainingObjectives,fail);return()=>{a();b();c();d();e();f();g();}},[]);
  const instructors=resources.filter(item=>item.kind==="instructor");
  const rooms=resources.filter(item=>item.kind==="room");
  const selectedCohort=cohorts.find(item=>item.id===session.cohortId);
  const selectedObjectiveProgram=[...OFFICIAL_PROGRAMS,...managedPrograms].find(item=>item.id===cohort.program||item.name===cohort.program);
  const participantIds=useMemo(()=>Array.from(new Set([...(selectedCohort?.studentIds||[]),...session.studentIds])),[selectedCohort,session.studentIds]);
  const toggle=(values:string[],id:string)=>values.includes(id)?values.filter(item=>item!==id):[...values,id];
  function effectiveSession(item:TheorySession){if(!item.cohortId)return item;const cohortMembers=cohorts.find(value=>value.id===item.cohortId)?.studentIds||[];const additional=item.additionalParticipantsVersion===2?(item.additionalStudentIds||[]):[];const studentIds=Array.from(new Set([...cohortMembers,...additional]));return{...item,studentIds,studentNames:studentIds.map(id=>students.find(value=>value.id===id)?.name||id),additionalStudentIds:additional,attendance:Object.fromEntries(Object.entries(item.attendance).filter(([id])=>studentIds.includes(id)))};}
  function editSession(item:TheorySession){const effective=effectiveSession(item);setEditingSessionId(item.id);setSession({title:item.title,program:item.program,topic:item.topic,date:item.date,startTime:item.startTime,endTime:item.endTime,instructorId:item.instructorId,roomId:item.roomId,cohortId:item.cohortId,studentIds:[...(effective.additionalStudentIds||[])],notes:item.notes});setMessage(`Modification de la session « ${item.title} ».`);setError("");}
  function cancelSessionEdit(){setEditingSessionId("");setSession({title:"",program:"",topic:"",date:today(),startTime:"09:00",endTime:"12:00",instructorId:"",roomId:"",cohortId:"",studentIds:[],notes:""});setMessage("");}
  useEffect(()=>{if(requestedSessionHandled.current||!sessions.length)return;const id=new URLSearchParams(window.location.search).get("session");if(!id)return;const item=sessions.find(value=>value.id===id);if(item){requestedSessionHandled.current=true;editSession(item);window.scrollTo({top:0,behavior:"smooth"})}},[sessions]);
  async function submitCohort(event:React.FormEvent){
    event.preventDefault();if(!cohort.name.trim()||!cohort.studentIds.length){setMessage("Le nom et au moins un étudiant sont obligatoires.");return;}
    const value={...cohort,id:cohort.id||`cohort-${Date.now()}`};await saveTheoryCohort(value);setCohort({id:"",name:"",program:"",studentIds:[]});setMessage("Cohorte enregistrée.");
  }
  async function submitSession(event:React.FormEvent){
    event.preventDefault();setMessage("");
    if(!session.title.trim()||!session.date||!session.instructorId||!participantIds.length){setMessage("Le cours, la date, l’instructeur et au moins un étudiant sont obligatoires.");return;}
    const start=minutes(session.startTime),end=minutes(session.endTime);if(end<=start){setMessage("L’heure de fin doit être après l’heure de début.");return;}
    const conflict=events.find(item=>item.theoreticalSessionId!==editingSessionId&&item.date===session.date&&item.startMinutes<end&&start<item.endMinutes&&(item.instructorId===session.instructorId||!!(session.roomId&&item.roomId===session.roomId)||participantIds.some(id=>eventStudents(item).includes(id))));
    if(conflict){
      const overlappingIds=participantIds.filter(id=>eventStudents(conflict).includes(id));
      const overlappingNames=overlappingIds.map(id=>students.find(item=>item.id===id)?.name||id);
      const instructorConflict=conflict.instructorId===session.instructorId;
      const roomConflict=!!session.roomId&&conflict.roomId===session.roomId;
      const reasons=[
        overlappingNames.length?`Étudiant${overlappingNames.length>1?"s":""} déjà réservé${overlappingNames.length>1?"s":""} : ${overlappingNames.join(", ")}`:"",
        instructorConflict?`Instructeur déjà réservé : ${instructors.find(item=>item.id===session.instructorId)?.name||session.instructorId}`:"",
        roomConflict?`Local déjà réservé : ${rooms.find(item=>item.id===session.roomId)?.name||session.roomId}`:""
      ].filter(Boolean);
      setMessage(`Conflit avec « ${conflict.title} » — ${reasons.join(" · ")}.`);
      return;
    }
    const instructor=instructors.find(item=>item.id===session.instructorId);
    const room=rooms.find(item=>item.id===session.roomId);
    const previous=sessions.find(item=>item.id===editingSessionId);
    const value:TheorySession={id:editingSessionId||`session-${Date.now()}`,title:session.title.trim(),program:session.program.trim(),topic:session.topic.trim(),date:session.date,startTime:session.startTime,endTime:session.endTime,instructorId:session.instructorId,instructorName:instructor?.name||session.instructorId,roomId:session.roomId,roomName:room?.name||"",cohortId:selectedCohort?.id||"",cohortName:selectedCohort?.name||"",studentIds:participantIds,studentNames:participantIds.map(id=>students.find(item=>item.id===id)?.name||id),additionalStudentIds:session.studentIds,additionalParticipantsVersion:2,attendance:previous?.attendance||{},status:previous?.status||"Planifiée",notes:session.notes.trim()};
    const wasEditing=Boolean(editingSessionId);await saveTheorySession(value);setEditingSessionId("");setSession({title:"",program:"",topic:"",date:today(),startTime:"09:00",endTime:"12:00",instructorId:"",roomId:"",cohortId:"",studentIds:[],notes:""});setMessage(wasEditing?"Session et bloc d’horaire modifiés.":"Session créée et ajoutée à l’horaire.");
  }
  function openAttendance(item:TheorySession){const effective=effectiveSession(item);setAttendanceSession(effective);setAttendanceForm(Object.fromEntries(effective.studentIds.filter(id=>effective.attendance[id]).map(id=>[id,effective.attendance[id]])));}
  async function completeSession(){
    if(!attendanceSession)return;
    const missing=attendanceSession.studentIds.filter(id=>!attendanceForm[id]);if(missing.length){const names=missing.map(id=>students.find(item=>item.id===id)?.name||id);window.alert(`Indiquez Présent ou Absent pour : ${names.join(", ")}.`);return;}
    await saveTheorySession({...attendanceSession,attendance:attendanceForm,status:"Complétée"});
    setAttendanceSession(null);setAttendanceForm({});setMessage("Présences consignées et session complétée.");
  }
  return <><PageHeader title="Formation théorique" subtitle="Cohortes, séances, instructeurs et registre des présences"/>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
    <section className="card theory-cohort-editor"><label>Modifier une cohorte existante<select value={cohort.id} onChange={event=>{const selected=cohorts.find(item=>item.id===event.target.value);setCohort(selected?{...selected,studentIds:[...selected.studentIds]}:{id:"",name:"",program:"",studentIds:[]})}}><option value="">Créer une nouvelle cohorte</option>{cohorts.map(item=><option value={item.id} key={item.id}>{item.name} · {item.studentIds.length} étudiant(s)</option>)}</select></label>{cohort.id&&<div><span className="badge ok">Modification de « {cohort.name} »</span><button className="button secondary small" onClick={()=>setCohort({id:"",name:"",program:"",studentIds:[]})}>Annuler la modification</button></div>}</section>
    {cohort.id&&(selectedObjectiveProgram?<CohortTrainingObjectivesPanel cohortId={cohort.id} cohortName={cohort.name} program={selectedObjectiveProgram} objectives={trainingObjectives}/>:<section className="card"><h2>Objectifs de progression — {cohort.name}</h2><p>Associez cette cohorte à l’identifiant ou au nom exact d’un programme existant pour gérer ses ajustements.</p></section>)}
    <section className="card theory-cohort-editor"><label>Modifier une session existante<select value={editingSessionId} onChange={event=>{const selected=sessions.find(item=>item.id===event.target.value);if(selected)editSession(selected);else cancelSessionEdit()}}><option value="">Créer une nouvelle session</option>{sessions.slice().sort((a,b)=>`${b.date}${b.startTime}`.localeCompare(`${a.date}${a.startTime}`)).map(item=><option value={item.id} key={item.id}>{item.date} · {item.startTime} — {item.title}</option>)}</select></label>{editingSessionId&&<div><span className="badge warn">Session en modification</span><button className="button" onClick={()=>document.querySelectorAll<HTMLFormElement>("form.theory-form")[1]?.requestSubmit()}>Enregistrer les modifications</button><button className="button secondary small" onClick={cancelSessionEdit}>Annuler</button></div>}</section>
    <div className="theory-layout">
      <form className="card theory-form" onSubmit={submitCohort}><h2>Créer une cohorte</h2><label>Nom de la cohorte<input required value={cohort.name} onChange={e=>setCohort({...cohort,name:e.target.value})} placeholder="Ex. ATP(A) — Automne 2026"/></label><label>Programme<input value={cohort.program} onChange={e=>setCohort({...cohort,program:e.target.value})}/></label><fieldset><legend>Étudiants de la cohorte</legend><div className="theory-student-list">{students.map(item=><label key={item.id}><input type="checkbox" checked={cohort.studentIds.includes(item.id)} onChange={()=>setCohort({...cohort,studentIds:toggle(cohort.studentIds,item.id)})}/>{item.name}</label>)}</div></fieldset><button className="button">Enregistrer la cohorte</button></form>
      <form className="card theory-form" onSubmit={submitSession}><h2>Planifier une session</h2><div className="form-grid"><label>Cours<input required value={session.title} onChange={e=>setSession({...session,title:e.target.value})} placeholder="Ex. Météorologie 1"/></label><label>Programme théorique<input value={session.program} onChange={e=>setSession({...session,program:e.target.value})}/></label><label>Date<input type="date" required value={session.date} onChange={e=>setSession({...session,date:e.target.value})}/></label><label>Instructeur<select required value={session.instructorId} onChange={e=>setSession({...session,instructorId:e.target.value})}><option value="">Sélectionner</option>{instructors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Local / salle<select value={session.roomId} onChange={e=>setSession({...session,roomId:e.target.value})}><option value="">Aucun local</option>{rooms.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Début<input type="time" required value={session.startTime} onChange={e=>setSession({...session,startTime:e.target.value})}/></label><label>Fin<input type="time" required value={session.endTime} onChange={e=>setSession({...session,endTime:e.target.value})}/></label></div><label>Sujet / contenu<textarea value={session.topic} onChange={e=>setSession({...session,topic:e.target.value})}/></label><label>Cohorte<select value={session.cohortId} onChange={e=>setSession({...session,cohortId:e.target.value})}><option value="">Aucune — sélection individuelle</option>{cohorts.map(item=><option value={item.id} key={item.id}>{item.name} ({item.studentIds.length})</option>)}</select></label><fieldset><legend>Étudiants ajoutés individuellement</legend><div className="theory-student-list">{students.map(item=><label key={item.id}><input type="checkbox" checked={session.studentIds.includes(item.id)} onChange={()=>setSession({...session,studentIds:toggle(session.studentIds,item.id)})}/>{item.name}{selectedCohort?.studentIds.includes(item.id)?" · cohorte":""}</label>)}</div></fieldset><div className="theory-participant-count">{participantIds.length} participant(s) au total</div><label>Notes<textarea value={session.notes} onChange={e=>setSession({...session,notes:e.target.value})}/></label><button className="button">Créer la session dans l’horaire</button></form>
    </div>
    <section className="card"><h2>Cohortes</h2><div className="theory-cohort-grid">{cohorts.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.program||"Programme non précisé"} · {item.studentIds.length} étudiant(s)</span></div><button className="icon-button" onClick={()=>confirm(`Supprimer ${item.name}?`)&&deleteTheoryCohort(item.id)}>×</button></article>)}{!cohorts.length&&<p>Aucune cohorte.</p>}</div></section>
    <section className="card"><h2>Registre des sessions</h2><div className="theory-session-list">{sessions.slice().sort((a,b)=>`${b.date}${b.startTime}`.localeCompare(`${a.date}${a.startTime}`)).map(item=>{const present=item.studentIds.filter(id=>item.attendance[id]==="Présent").length,absent=item.studentIds.filter(id=>item.attendance[id]==="Absent").length;return <article key={item.id}><div><strong>{item.date} · {item.startTime}–{item.endTime} — {item.title}</strong><span>{item.instructorName} · {item.roomName||"Aucun local"} · {item.cohortName||"Sélection individuelle"} · {item.studentIds.length} participant(s)</span><small>{item.topic}</small>{item.status==="Complétée"&&<small className="attendance-summary">Présents : {present} · Absents : {absent}</small>}</div><span className="status-badge">{item.status}</span>{item.status==="Planifiée"&&<button className="button secondary small" onClick={()=>openAttendance(item)}>Présences et compléter</button>}<button className="icon-button" onClick={()=>confirm(`Supprimer la session ${item.title}?`)&&deleteTheorySession(item)}>×</button></article>})}{!sessions.length&&<p>Aucune session théorique.</p>}</div></section>
    {attendanceSession&&<div className="modal-backdrop"><section className="modal attendance-modal"><header><div><h2>Feuille de présence</h2><p>{attendanceSession.title} · {attendanceSession.date} · {attendanceSession.startTime}–{attendanceSession.endTime}</p></div><button className="icon-button" onClick={()=>setAttendanceSession(null)}>×</button></header><div className="modal-body"><div className="attendance-list">{attendanceSession.studentIds.map((id,index)=>{const name=attendanceSession.studentNames[index]||students.find(item=>item.id===id)?.name||id;return <article key={id}><strong>{name}</strong><div><label className={attendanceForm[id]==="Présent"?"active present":""}><input type="radio" name={`attendance-${id}`} checked={attendanceForm[id]==="Présent"} onChange={()=>setAttendanceForm({...attendanceForm,[id]:"Présent"})}/>Présent</label><label className={attendanceForm[id]==="Absent"?"active absent":""}><input type="radio" name={`attendance-${id}`} checked={attendanceForm[id]==="Absent"} onChange={()=>setAttendanceForm({...attendanceForm,[id]:"Absent"})}/>Absent</label></div></article>})}</div></div><footer><span/><button className="button secondary" onClick={()=>setAttendanceSession(null)}>Annuler</button><button className="button" onClick={completeSession}>Consigner et compléter</button></footer></section></div>}
  </>;
}
