import type{InstructorClass}from"@/features/instructors/types";

const date=(value:string)=>new Date(`${value}T00:00:00Z`);
const iso=(value:Date)=>value.toISOString().slice(0,10);
const addDays=(value:string,days:number)=>{const result=date(value);result.setUTCDate(result.getUTCDate()+days);return iso(result)};
const addMonths=(value:string,months:number)=>{const source=date(value),day=source.getUTCDate(),result=new Date(Date.UTC(source.getUTCFullYear(),source.getUTCMonth()+months,1));const last=new Date(Date.UTC(result.getUTCFullYear(),result.getUTCMonth()+1,0)).getUTCDate();result.setUTCDate(Math.min(day,last));return iso(result)};
const firstOfNextMonth=(value:string)=>{const source=date(value);return iso(new Date(Date.UTC(source.getUTCFullYear(),source.getUTCMonth()+1,1)))};
const withinRenewalWindow=(eventDate:string,previousExpiry?:string)=>Boolean(previousExpiry&&eventDate<=previousExpiry&&eventDate>=addDays(previousExpiry,-90));
export const ageOn=(birthDate:string,onDate:string)=>{const birth=date(birthDate),on=date(onDate);let age=on.getUTCFullYear()-birth.getUTCFullYear();if(on.getUTCMonth()<birth.getUTCMonth()||(on.getUTCMonth()===birth.getUTCMonth()&&on.getUTCDate()<birth.getUTCDate()))age-=1;return age};
export function calculateOrizonMedicalExpiry(medicalExamDate:string,birthDate:string,previousExpiry?:string){if(!medicalExamDate||!birthDate)return null;const months=ageOn(birthDate,medicalExamDate)>=40?6:12,base=withinRenewalWindow(medicalExamDate,previousExpiry)?previousExpiry!:firstOfNextMonth(medicalExamDate);return{expiresAt:addMonths(base,months),months,renewalWindowApplied:base===previousExpiry};}
const classMonths:Record<InstructorClass,number>={"Classe 4":12,"Classe 3":24,"Classe 2":36,"Classe 1":48};
export function calculateInstructorRatingExpiry(testDate:string,instructorClass:InstructorClass,previousExpiry?:string){if(!testDate)return null;const months=classMonths[instructorClass],base=withinRenewalWindow(testDate,previousExpiry)?previousExpiry!:firstOfNextMonth(testDate);return{expiresAt:addMonths(base,months),months,renewalWindowApplied:base===previousExpiry};}
export type IfrInstrumentExperience={instrumentHours:number;instrumentApproaches:number};
export function calculateIfrRecency(eventDate:string,instrumentExperience?:IfrInstrumentExperience,today=new Date().toISOString().slice(0,10)){if(!eventDate)return null;const cycleEnd=addMonths(eventDate,24),sixSixRequiredFrom=addMonths(firstOfNextMonth(eventDate),12),days=Math.round((date(cycleEnd).getTime()-date(today).getTime())/86400000),hoursCompliant=(instrumentExperience?.instrumentHours||0)>=6,approachesCompliant=(instrumentExperience?.instrumentApproaches||0)>=6;if(today>cycleEnd)return{cycleEnd,sixSixRequiredFrom,hoursCompliant,approachesCompliant,status:"not-current" as const,days};if(today<sixSixRequiredFrom)return{cycleEnd,sixSixRequiredFrom,hoursCompliant,approachesCompliant,status:days<=90?"expiring" as const:"recent" as const,days};if(!hoursCompliant||!approachesCompliant)return{cycleEnd,sixSixRequiredFrom,hoursCompliant,approachesCompliant,status:"six-six-missing" as const,days};return{cycleEnd,sixSixRequiredFrom,hoursCompliant,approachesCompliant,status:"six-six-required" as const,days};}
