"use client";
import{useEffect,useMemo,useState}from"react";
import{useAuth}from"@/features/auth/AuthProvider";
import type{Instructor,InstructorClass}from"@/features/instructors/types";
import{saveEmployeeCompliance,subscribeEmployeeCompliance}from"./firestore";
import{calculateIfrRecency,calculateInstructorRatingExpiry,calculateOrizonMedicalExpiry}from"./complianceCalculations";
import type{EmployeeComplianceRecord,PayrollActor}from"./types";
import"./employeeCoreCompliance.css";

const today=()=>new Date().toISOString().slice(0,10);
export function EmployeeCoreCompliancePanel({instructor,manager}:{instructor:Instructor;manager:boolean}){
 const{user,profile}=useAuth(),actor:PayrollActor={uid:user?.uid||"",name:profile?.name||profile?.email||"",role:profile?.role||""};
 const[records,setRecords]=useState<EmployeeComplianceRecord[]>([]),[reason,setReason]=useState("Mise à jour du dossier de conformité"),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[medicalExam,setMedicalExam]=useState(""),[medicalOfficial,setMedicalOfficial]=useState(""),[medicalOverrideReason,setMedicalOverrideReason]=useState("");
 const[ratingClass,setRatingClass]=useState<InstructorClass>(instructor.classLevel),[ratingTest,setRatingTest]=useState(""),[ratingOfficial,setRatingOfficial]=useState(""),[renewalMethod,setRenewalMethod]=useState("");
 const[ifrHeld,setIfrHeld]=useState(false),[ifrGroup,setIfrGroup]=useState("Groupe 1"),[eventType,setEventType]=useState<"Test en vol IFR"|"IPC"|"PPC"|"PCC"|"Autre">("IPC"),[eventDate,setEventDate]=useState(""),[instrumentHours,setInstrumentHours]=useState(0),[instrumentApproaches,setInstrumentApproaches]=useState(0),[experienceAsOf,setExperienceAsOf]=useState(today());
 useEffect(()=>subscribeEmployeeCompliance(instructor.id,setRecords,value=>setError(value.message)),[instructor.id]);
 const medical=records.find(item=>item.recordType==="medical"),rating=records.find(item=>item.recordType==="instructor-rating"),ifr=records.find(item=>item.recordType==="ifr-recency");
 useEffect(()=>{if(medical?.recordType==="medical"){setMedicalExam(medical.examDate);setMedicalOfficial(medical.officialExpiry||"");setMedicalOverrideReason(medical.manualOverrideReason||"")}if(rating?.recordType==="instructor-rating"){setRatingClass(rating.instructorClass);setRatingTest(rating.testDate);setRatingOfficial(rating.officialExpiry||"");setRenewalMethod(rating.renewalMethod||"")}if(ifr?.recordType==="ifr-recency"){setIfrHeld(ifr.ifrHeld);setIfrGroup(ifr.ifrGroup);setEventType(ifr.eventType);setEventDate(ifr.eventDate);setInstrumentHours(ifr.instrumentHours);setInstrumentApproaches(ifr.instrumentApproaches);setExperienceAsOf(ifr.instrumentExperienceAsOf||today())}},[medical,rating,ifr]);
 const medicalCalc=useMemo(()=>calculateOrizonMedicalExpiry(medicalExam,instructor.birthDate,medical?.recordType==="medical"?(medical.officialExpiry||medical.calculatedExpiry):undefined),[medicalExam,instructor.birthDate,medical]);
 const ratingCalc=useMemo(()=>calculateInstructorRatingExpiry(ratingTest,ratingClass,rating?.recordType==="instructor-rating"?(rating.officialExpiry||rating.calculatedExpiry):undefined),[ratingTest,ratingClass,rating]);
 const ifrCalc=useMemo(()=>calculateIfrRecency(eventDate,{instrumentHours,instrumentApproaches}),[eventDate,instrumentHours,instrumentApproaches]);
 async function persist(value:EmployeeComplianceRecord){if(!user)return;try{await saveEmployeeCompliance(value,actor,reason);setMessage("Conformité enregistrée et historisée.");setError("")}catch(caught){setError(caught instanceof Error?caught.message:"Enregistrement impossible.")}}
 async function saveMedical(){if(!medicalCalc){setError(instructor.birthDate?"Date d’examen médical requise.":"Date de naissance requise.");return}if(medicalOfficial&&medicalOfficial!==medicalCalc.expiresAt&&!medicalOverrideReason.trim()){setError("Un motif est obligatoire pour remplacer l’échéance calculée.");return}await persist({id:`${instructor.id}:medical`,employeeId:instructor.id,recordType:"medical",examDate:medicalExam,calculatedExpiry:medicalCalc.expiresAt,officialExpiry:medicalOfficial||undefined,manualOverrideReason:medicalOfficial&&medicalOfficial!==medicalCalc.expiresAt?medicalOverrideReason:undefined,previousExpiry:medical?.recordType==="medical"?(medical.officialExpiry||medical.calculatedExpiry):undefined,updatedBy:actor,updatedAt:""})}
 async function saveRating(){if(!ratingCalc){setError("Date du test ou renouvellement requise.");return}if(ratingOfficial&&ratingOfficial!==ratingCalc.expiresAt&&!reason.trim()){setError("Un motif est obligatoire pour remplacer l’échéance calculée.");return}await persist({id:`${instructor.id}:instructor-rating`,employeeId:instructor.id,recordType:"instructor-rating",instructorClass:ratingClass,testDate:ratingTest,calculatedExpiry:ratingCalc.expiresAt,officialExpiry:ratingOfficial||undefined,renewalMethod:renewalMethod||undefined,manualOverrideReason:ratingOfficial&&ratingOfficial!==ratingCalc.expiresAt?reason:undefined,previousExpiry:rating?.recordType==="instructor-rating"?(rating.officialExpiry||rating.calculatedExpiry):undefined,updatedBy:actor,updatedAt:""})}
 async function saveIfr(){if(ifrHeld&&!ifrCalc){setError("Date du dernier événement IFR requise.");return}await persist({id:`${instructor.id}:ifr-recency`,employeeId:instructor.id,recordType:"ifr-recency",ifrHeld,ifrGroup,eventType,eventDate:ifrHeld?eventDate:"",cycleEnd:ifrCalc?.cycleEnd||"",sixSixRequiredFrom:ifrCalc?.sixSixRequiredFrom||"",instrumentHours,instrumentApproaches,instrumentExperienceAsOf:experienceAsOf||undefined,updatedBy:actor,updatedAt:""})}
 return <section className="card core-compliance"><header><div><h2>Conformité instructeur</h2><p>Médical interne Orizon, qualification instructeur et récence IFR.</p></div></header>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
  <div className="core-compliance-grid"><section><h3>Médical — politique interne Orizon</h3>{!instructor.birthDate&&<div className="notice error">Date de naissance requise dans le dossier instructeur.</div>}<label>Date de naissance<input type="date" value={instructor.birthDate} readOnly/></label><label>Date examen médical<input type="date" value={medicalExam} disabled={!manager} onChange={event=>setMedicalExam(event.target.value)}/></label><label>Échéance calculée<input value={medicalCalc?.expiresAt||"Date de naissance requise"} readOnly/></label><label>Échéance officielle/manuelle<input type="date" value={medicalOfficial} disabled={!manager} onChange={event=>setMedicalOfficial(event.target.value)}/></label>{medicalOfficial&&medicalCalc&&medicalOfficial!==medicalCalc.expiresAt&&<label>Motif du remplacement<input value={medicalOverrideReason} disabled={!manager} onChange={event=>setMedicalOverrideReason(event.target.value)}/></label>}{manager&&<button className="button" onClick={saveMedical}>Enregistrer le médical</button>}</section>
  <section><h3>Qualification instructeur</h3><label>Classe<select value={ratingClass} disabled={!manager} onChange={event=>setRatingClass(event.target.value as InstructorClass)}><option>Classe 4</option><option>Classe 3</option><option>Classe 2</option><option>Classe 1</option></select></label><label>Date du test / renouvellement<input type="date" value={ratingTest} disabled={!manager} onChange={event=>setRatingTest(event.target.value)}/></label><label>Échéance calculée<input value={ratingCalc?.expiresAt||"—"} readOnly/></label><label>Échéance officielle/manuelle<input type="date" value={ratingOfficial} disabled={!manager} onChange={event=>setRatingOfficial(event.target.value)}/></label><label>Méthode de renouvellement<input value={renewalMethod} disabled={!manager} onChange={event=>setRenewalMethod(event.target.value)}/></label>{manager&&<button className="button" onClick={saveRating}>Enregistrer la qualification</button>}</section>
  <section><h3>Qualification / récence IFR</h3><label className="active-check"><input type="checkbox" checked={ifrHeld} disabled={!manager} onChange={event=>setIfrHeld(event.target.checked)}/>Qualification IFR détenue</label><label>Groupe IFR<input value={ifrGroup} disabled={!manager||!ifrHeld} onChange={event=>setIfrGroup(event.target.value)}/></label><label>Type du dernier événement<select value={eventType} disabled={!manager||!ifrHeld} onChange={event=>setEventType(event.target.value as typeof eventType)}><option>Test en vol IFR</option><option>IPC</option><option>PPC</option><option>PCC</option><option>Autre</option></select></label><label>Date événement<input type="date" value={eventDate} disabled={!manager||!ifrHeld} onChange={event=>setEventDate(event.target.value)}/></label><div className="compliance-calculated"><span>Fin du cycle 24 mois</span><strong>{ifrCalc?.cycleEnd||"—"}</strong><span>6/6 requis à partir du</span><strong>{ifrCalc?.sixSixRequiredFrom||"—"}</strong></div><label>Heures instruments — 6 derniers mois<input type="number" min="0" step="0.1" value={instrumentHours} disabled={!manager||!ifrHeld} onChange={event=>setInstrumentHours(Number(event.target.value))}/></label><label>Approches instruments — 6 derniers mois<input type="number" min="0" step="1" value={instrumentApproaches} disabled={!manager||!ifrHeld} onChange={event=>setInstrumentApproaches(Number(event.target.value))}/></label><label>Données à jour au<input type="date" value={experienceAsOf} disabled={!manager||!ifrHeld} onChange={event=>setExperienceAsOf(event.target.value)}/></label><strong className={`ifr-state ${ifrCalc?.status||"none"}`}>{!ifrHeld?"IFR non détenu / non consigné":ifrCalc?.status==="recent"?"IFR récent — aucune vérification 6/6 requise":ifrCalc?.status==="six-six-required"?"IFR — 6/6 conforme":ifrCalc?.status==="six-six-missing"?"IFR non récent — 6/6 non conforme":ifrCalc?.status==="not-current"?"IFR non récent — événement requis":"Échéance IFR à moins de 90 jours"}</strong>{manager&&<button className="button" onClick={saveIfr}>Enregistrer la récence IFR</button>}</section></div>
  {manager&&<label className="compliance-reason">Motif de la modification<input required value={reason} onChange={event=>setReason(event.target.value)}/></label>}
 </section>;
}
