"use client";
import{useEffect,useState}from"react";
import{useAuth}from"@/features/auth/AuthProvider";
import{saveEmployeeAircraftQualification,subscribeEmployeeAircraftQualifications}from"./firestore";
import{statusForExpiry}from"./staffCompliance";
import type{EmployeeAircraftQualification,PayrollActor}from"./types";
import"./employeeAircraftQualifications.css";

const aircraftTypes=["C152","C172","PA31","Autre"];
const today=()=>new Date().toISOString().slice(0,10);
const empty=(employeeId:string,actor:PayrollActor):EmployeeAircraftQualification=>({id:`qualification-${crypto.randomUUID()}`,employeeId,aircraftType:"C152",qualificationType:"aircraft",qualificationName:"Formation sur type C152",completedAt:today(),expiresAt:undefined,status:"valid",notes:"",source:"employee-aircraft-qualification",createdBy:actor,createdAt:"",updatedBy:actor,updatedAt:""});
const labelFor=(value:EmployeeAircraftQualification)=>value.qualificationType==="flight"?`PPC ${value.aircraftType}`:`Formation sur type ${value.aircraftType}`;
const displayState=(value:EmployeeAircraftQualification)=>value.status==="not-applicable"?"not-applicable":statusForExpiry(value.expiresAt);
const stateLabel={valid:"Valide",expiring:"Expire bientôt",expired:"Expirée",missing:"Manquante","not-applicable":"Non applicable"};

export function EmployeeAircraftQualificationsPanel({employeeId,employeeName,manager}:{employeeId:string;employeeName:string;manager:boolean}){
 const{user,profile}=useAuth(),actor:PayrollActor={uid:user?.uid||"",name:profile?.name||profile?.email||"",role:profile?.role||""};
 const[items,setItems]=useState<EmployeeAircraftQualification[]>([]),[editing,setEditing]=useState<EmployeeAircraftQualification|null>(null),[reason,setReason]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{setItems([]);if(!employeeId)return;return subscribeEmployeeAircraftQualifications(employeeId,setItems,value=>setError(value.message))},[employeeId]);
 function open(value?:EmployeeAircraftQualification,renew=false){const draft=value?{...value}:empty(employeeId,actor);if(renew){draft.completedAt=today();draft.expiresAt="";draft.status="valid"}setEditing(draft);setReason(value?renew?"Renouvellement de la qualification":"Mise à jour du dossier":"Ajout au dossier");setError("");setMessage("")}
 async function save(){if(!editing||!user)return;try{const value={...editing,qualificationName:labelFor(editing),expiresAt:editing.expiresAt||undefined,status:editing.status};await saveEmployeeAircraftQualification(value,actor,reason);setEditing(null);setMessage("Qualification enregistrée et ajoutée à l’historique.")}catch(value){setError(value instanceof Error?value.message:"Enregistrement impossible.")}}
 async function markNotApplicable(value:EmployeeAircraftQualification){if(!user)return;const auditReason=window.prompt("Raison du changement vers « Non applicable » :", "Non applicable pour cet employé");if(!auditReason)return;try{await saveEmployeeAircraftQualification({...value,status:"not-applicable"},actor,auditReason);setMessage("Qualification marquée non applicable.")}catch(caught){setError(caught instanceof Error?caught.message:"Modification impossible.")}}
 return <section className="card aircraft-qualification-register"><header><div><h2>Qualifications / formations sur type</h2><p>Données utilisées automatiquement dans la Vue du personnel.</p></div>{manager&&employeeId&&<button className="button" onClick={()=>open()}>Ajouter</button>}</header>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
  <div className="aircraft-qualification-table"><div className="aircraft-qualification-row head"><span>Type</span><span>Qualification</span><span>Date obtenue</span><span>Échéance</span><span>État</span><span>Action</span></div>{items.map(item=>{const state=displayState(item);return <div className="aircraft-qualification-row" key={item.id}><strong>{item.aircraftType}</strong><span>{item.qualificationName}</span><span>{item.completedAt||"—"}</span><span>{item.expiresAt||"Sans échéance"}</span><span className={`staff-compliance-badge ${state}`}><i/>{stateLabel[state]}</span><div className="aircraft-qualification-actions">{manager&&<><button className="button secondary small" onClick={()=>open(item)}>Modifier</button><button className="button secondary small" onClick={()=>open(item,true)}>Renouveler</button>{item.status!=="not-applicable"&&<button className="button secondary small" onClick={()=>markNotApplicable(item)}>Non applicable</button>}</>}</div></div>})}{!items.length&&<p>Aucune qualification sur type consignée pour {employeeName||"cet employé"}.</p>}</div>
  {editing&&<div className="modal-backdrop"><section className="modal aircraft-qualification-modal"><header><div><h2>{items.some(item=>item.id===editing.id)?"Modifier la qualification":"Ajouter une qualification"}</h2><p>{employeeName}</p></div><button className="icon-button" onClick={()=>setEditing(null)}>×</button></header><div className="modal-body"><div className="form-grid"><label>Type d’avion<select value={editing.aircraftType} onChange={event=>setEditing({...editing,aircraftType:event.target.value})}>{aircraftTypes.map(item=><option key={item}>{item}</option>)}</select></label><label>Qualification<select value={editing.qualificationType} onChange={event=>setEditing({...editing,qualificationType:event.target.value as EmployeeAircraftQualification["qualificationType"]})}><option value="aircraft">Formation sur type</option><option value="flight">PPC</option></select></label><label>Date obtenue<input type="date" value={editing.completedAt||""} onChange={event=>setEditing({...editing,completedAt:event.target.value||undefined})}/></label><label>Échéance<input type="date" value={editing.expiresAt||""} onChange={event=>setEditing({...editing,expiresAt:event.target.value||undefined})}/><small>Laisser vide pour une qualification sans échéance.</small></label><label>État<select value={editing.status} onChange={event=>setEditing({...editing,status:event.target.value as EmployeeAircraftQualification["status"]})}><option value="valid">Applicable</option><option value="not-applicable">Non applicable</option></select></label><label className="wide">Raison de l’ajout ou modification<input required value={reason} onChange={event=>setReason(event.target.value)}/></label></div><label>Notes<textarea value={editing.notes||""} onChange={event=>setEditing({...editing,notes:event.target.value})}/></label></div><footer><span/><button className="button secondary" onClick={()=>setEditing(null)}>Annuler</button><button className="button" disabled={!reason.trim()||!editing.aircraftType} onClick={save}>Enregistrer</button></footer></section></div>}
 </section>;
}
