"use client";
import {useEffect,useMemo,useState}from"react";
import{useAuth}from"@/features/auth/AuthProvider";
import{subscribeInstructors}from"@/features/instructors/firestore";
import type{Instructor}from"@/features/instructors/types";
import{confirmPayrollExport,ensurePayrollPeriod,ensurePayrollPeriodsForEntries,lockPayrollPeriod,logPayrollAction,subscribePayPeriods,subscribePayrollExports,subscribePayrollProfiles,subscribeTimeEntries}from"./firestore";
import{payrollPeriodForDate}from"./payPeriods";
import{generatePayrollCsv,payrollChecksum,PAYROLL_EXPORT_VERSION,preparePayrollExport}from"./payrollExport";
import type{EmployeePayrollProfile,PayPeriod,PayrollActor,PayrollExport,TimeEntry}from"./types";

type Generated={csv:string;checksum:string;fileName:string;summary:ReturnType<typeof preparePayrollExport>};
const money=(value:number)=>value.toLocaleString("fr-CA",{style:"currency",currency:"CAD"});
export function PayrollExportPanel(){
 const{user,profile}=useAuth(),authorized=profile?.role==="Administrateur"||profile?.role==="Chef instructeur",actor:PayrollActor={uid:user?.uid||"",name:profile?.name||profile?.email||"Utilisateur",role:profile?.role||""};
 const[entries,setEntries]=useState<TimeEntry[]>([]),[profiles,setProfiles]=useState<EmployeePayrollProfile[]>([]),[periods,setPeriods]=useState<PayPeriod[]>([]),[exports,setExports]=useState<PayrollExport[]>([]),[instructors,setInstructors]=useState<Instructor[]>([]);
 const[selected,setSelected]=useState(""),[generated,setGenerated]=useState<Generated|null>(null),[dialog,setDialog]=useState<{action:"confirm"|"lock";reason:string}|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>subscribeTimeEntries(undefined,true,setEntries,value=>setError(value.message)),[]);useEffect(()=>subscribePayrollProfiles(undefined,true,setProfiles,value=>setError(value.message)),[]);useEffect(()=>subscribePayPeriods(setPeriods,value=>setError(value.message)),[]);useEffect(()=>subscribePayrollExports(setExports,value=>setError(value.message)),[]);useEffect(()=>subscribeInstructors({next:setInstructors,error:value=>setError(value.message)}),[]);
 const periodIds=useMemo(()=>periods.map(item=>item.id),[periods]);useEffect(()=>{if(!authorized||!user)return;const current=payrollPeriodForDate(new Date().toISOString().slice(0,10));ensurePayrollPeriod(current,actor).then(()=>entries.length?ensurePayrollPeriodsForEntries(entries,actor):undefined).catch(value=>setError(value instanceof Error?value.message:"Création de la période impossible."));},[authorized,user,entries]);useEffect(()=>{if(!selected&&periodIds.length)setSelected(periodIds[0])},[periodIds,selected]);useEffect(()=>setGenerated(null),[selected]);
 const payrollIds=useMemo(()=>Object.fromEntries([...new Set(entries.map(item=>item.employeeId))].map(id=>[id,profiles.find(item=>item.employeeId===id)?.payrollEmployeeId||instructors.find(item=>item.id===id)?.employeeNumber||""])),[entries,profiles,instructors]);
 const summary=useMemo(()=>preparePayrollExport(entries,selected,payrollIds),[entries,selected,payrollIds]),period=periods.find(item=>item.id===selected),periodExports=exports.filter(item=>item.payPeriodId===selected);
 const generate=async()=>{setBusy(true);setError("");try{if(summary.criticalAnomalies.length){await logPayrollAction(selected,"Tentative export bloquée",actor,"Anomalies critiques avant export.",{anomalies:summary.criticalAnomalies});throw new Error(summary.criticalAnomalies.join(" "));}const csv=generatePayrollCsv(summary.rows),checksum=await payrollChecksum(csv),fileName=`flight-director-paie-${selected}-${summary.periodStart}-${summary.periodEnd}.csv`,blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=fileName;link.click();URL.revokeObjectURL(url);setGenerated({csv,checksum,fileName,summary});await logPayrollAction(selected,periodExports.length?"Réexport CSV généré":"Export CSV généré",actor,"Génération demandée par l’administration.",{checksum,fileName,entryCount:summary.entryCount});setMessage("CSV généré. Vérifiez-le puis confirmez explicitement l’export.");}catch(value){setError(value instanceof Error?value.message:"Export impossible.");}finally{setBusy(false)}};
 const confirm=async()=>{if(!dialog)return;setBusy(true);setError("");try{if(dialog.action==="confirm"){if(!generated)throw new Error("Générez d’abord le fichier CSV à confirmer.");await confirmPayrollExport({payPeriodId:selected,format:"CSV",entryCount:generated.summary.entryCount,employeeCount:generated.summary.employeeCount,totalHours:generated.summary.totalHours,totalAmount:generated.summary.totalAmount,generatedBy:actor,checksum:generated.checksum,fileName:generated.fileName,version:PAYROLL_EXPORT_VERSION},actor,dialog.reason,generated.summary.periodStart,generated.summary.periodEnd);setGenerated(null);setMessage("Export confirmé et preuve Firestore créée.");}else{await lockPayrollPeriod(selected,actor,dialog.reason);setMessage("Période verrouillée. Toute correction future devra être un ajustement dans une période ouverte.");}setDialog(null);}catch(value){await logPayrollAction(selected,"Tentative d’action paie bloquée",actor,value instanceof Error?value.message:"Action impossible.",{action:dialog.action}).catch(()=>undefined);setError(value instanceof Error?value.message:"Action impossible.");}finally{setBusy(false)}};
 if(!authorized)return <div className="notice error">Export réservé à l’administration ou à la comptabilité autorisée.</div>;
 return <section className="employee-workspace payroll-export"><div className="card employee-section-head"><div><h2>Export comptabilité</h2><p>Flight Director est la source unique. Préparation, preuve et verrouillage final de la paie.</p></div></div>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
  <section className="card export-controls"><label>Période<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choisir…</option>{periodIds.map(id=><option key={id}>{id}</option>)}</select></label><span className="badge">{period?.status||"Ouverte"}</span><span>{periodExports.length} export(s) confirmé(s)</span></section>
  {selected&&<><div className="timesheet-summary"><article className="card"><span>Employés approuvés</span><strong>{summary.employeeCount}</strong></article><article className="card"><span>Employés en attente</span><strong>{summary.pendingEmployeeCount}</strong></article><article className="card"><span>Entrées</span><strong>{summary.entryCount}</strong></article><article className="card"><span>Heures</span><strong>{summary.totalHours.toFixed(2)}</strong></article><article className="card"><span>Primes</span><strong>{money(summary.totalPremiums)}</strong></article><article className="card total"><span>Montant</span><strong>{money(summary.totalAmount)}</strong></article></div>
  <section className="card"><h3>Anomalies restantes</h3>{summary.anomalies.length?<ul>{summary.anomalies.map(item=><li key={item}>{item}</li>)}</ul>:<p className="badge ok">Aucune anomalie</p>}</section>
  <section className="card export-actions"><button className="button" disabled={busy||!summary.entryCount||Boolean(summary.criticalAnomalies.length)} onClick={generate}>Générer CSV</button><button className="button" disabled={busy||!generated} onClick={()=>setDialog({action:"confirm",reason:""})}>Confirmer l’export</button><button className="button danger" disabled={busy||period?.status!=="Exportée"} onClick={()=>setDialog({action:"lock",reason:""})}>Verrouiller la période</button></section></>}
  {dialog&&<div className="modal-overlay"><section className="modal-card payroll-dialog"><header><h2>{dialog.action==="confirm"?"Confirmer l’export":"Verrouiller définitivement la période"}</h2><button onClick={()=>setDialog(null)}>×</button></header>{error&&<div className="notice error">{error}</div>}<label>Motif obligatoire<textarea rows={5} value={dialog.reason} onChange={event=>setDialog({...dialog,reason:event.target.value})}/></label><footer><button className="button secondary" onClick={()=>setDialog(null)}>Annuler</button><button className="button" disabled={busy||!dialog.reason.trim()} onClick={confirm}>Confirmer</button></footer></section></div>}
  <style jsx global>{`.export-controls,.export-actions{display:flex;align-items:end;gap:16px;flex-wrap:wrap}.export-controls label{min-width:300px}.export-actions{justify-content:flex-end}`}</style></section>;
}
