"use client";
import{useEffect,useMemo,useState}from"react";
import{subscribeAllInstructorDocuments,subscribeInstructors}from"@/features/instructors/firestore";
import type{Instructor,InstructorDocument}from"@/features/instructors/types";
import{EMPLOYEE_TRAINING_SUBJECTS}from"./EmployeeTrainingPanel";
import{subscribeEmployeeAircraftQualifications,subscribeEmployeeCompliance,subscribeEmployeeLeaves,subscribeEmployeeTraining}from"./firestore";
import type{EmployeeAircraftQualification,EmployeeComplianceRecord,EmployeeLeave,EmployeeQualification,EmployeeQualificationStatus,EmployeeTrainingRecord}from"./types";
import{AIRCRAFT_QUALIFICATIONS,buildStaffRows,rowCompliance,type StaffCategory,type StaffDeadline,type StaffRow}from"./staffCompliance";
import"./staffCompliance.css";

const statusLabel:Record<EmployeeQualificationStatus,string>={valid:"Valide",expiring:"Expire dans moins de 90 jours",expired:"Expirée",missing:"Requise, non consignée","not-applicable":"Non applicable"};
const trainingShort:Record<string,string>={"company-introduction":"Introduction","human-factors":"Facteurs humains","operations-training-manual":"Manuel exploitation","operational-control":"Contrôle opérationnel","emergency-procedures":"Procédures urgence",car:"RAC","aircraft-type":"Formation sur type","flight-following":"Suivi des vols","surface-contamination":"Contamination surfaces",cfit:"CFIT","high-altitude":"Haute altitude"};
function ComplianceBadge({item,compact=false,applicable=true}:{item?:EmployeeQualification;compact?:boolean;applicable?:boolean}){const status=!applicable?"not-applicable":item?.status||"missing";const title=`${item?.qualificationName||"Élément"} · ${statusLabel[status]}${item?.notes?` · ${item.notes}`:""}${item?.expiresAt?` · Prochaine exigence ${item.expiresAt}`:""}`;return <span className={`staff-compliance-badge ${status} ${compact?"compact":""}`} title={title} aria-label={title}><i aria-hidden="true"/>{!compact&&<span>{item?.expiresAt||statusLabel[status]}</span>}</span>}
function Deadline({value}:{value:StaffDeadline}){if(!value)return <span className="staff-deadline empty">Aucune échéance consignée</span>;const remaining=value.days<0?`Expiré depuis ${Math.abs(value.days)} j`:`${value.days} j restant${value.days>1?"s":""}`;return <span className={`staff-deadline ${value.status}`} title={`${value.name} · ${value.date}`}><strong>{value.name}</strong><span>{value.date} · {remaining}</span></span>}
const qualificationFor=(row:StaffRow,name:string)=>row.qualifications.find(item=>item.qualificationName===name);

export function StaffComplianceOverview({onOpenEmployee}:{onOpenEmployee:(id:string,isInstructor:boolean)=>void}){
 const[instructors,setInstructors]=useState<Instructor[]>([]),[documents,setDocuments]=useState<InstructorDocument[]>([]),[records,setRecords]=useState<EmployeeTrainingRecord[]>([]),[leaves,setLeaves]=useState<EmployeeLeave[]>([]),[aircraftQualifications,setAircraftQualifications]=useState<EmployeeAircraftQualification[]>([]),[compliance,setCompliance]=useState<EmployeeComplianceRecord[]>([]),[error,setError]=useState("");
 const[query,setQuery]=useState(""),[category,setCategory]=useState<StaffCategory|"Tous">("Tous"),[state,setState]=useState<"Tous"|"Actifs"|"Expire bientôt"|"Expiré"|"Élément manquant">("Tous"),[classFilter,setClassFilter]=useState("Toutes"),[qualification,setQualification]=useState("Toutes");
 useEffect(()=>subscribeInstructors({next:setInstructors,error:value=>setError(value.message)}),[]);useEffect(()=>subscribeAllInstructorDocuments({next:setDocuments,error:value=>setError(value.message)}),[]);useEffect(()=>subscribeEmployeeTraining(undefined,setRecords,value=>setError(value.message)),[]);useEffect(()=>subscribeEmployeeLeaves(undefined,true,setLeaves,value=>setError(value.message)),[]);useEffect(()=>subscribeEmployeeAircraftQualifications(undefined,setAircraftQualifications,value=>setError(value.message)),[]);useEffect(()=>subscribeEmployeeCompliance(undefined,setCompliance,value=>setError(value.message)),[]);
 const rows=useMemo(()=>buildStaffRows(instructors,documents,records,leaves,EMPLOYEE_TRAINING_SUBJECTS,aircraftQualifications,compliance),[instructors,documents,records,leaves,aircraftQualifications,compliance]);
 const qualificationColumns=useMemo(()=>[...AIRCRAFT_QUALIFICATIONS,...(["IFR","Multi"] as const).filter(name=>rows.some(row=>qualificationFor(row,name)))],[rows]);
 const complianceOptions=useMemo(()=>[...new Set([...EMPLOYEE_TRAINING_SUBJECTS.map(item=>item.label),...rows.flatMap(row=>row.qualifications.map(item=>item.qualificationName))])].sort(),[rows]);
 const visible=useMemo(()=>rows.filter(row=>{const flags=rowCompliance(row),needle=query.trim().toLowerCase(),selected=[...row.qualifications,...row.training].find(item=>item.qualificationName===qualification);return(!needle||row.name.toLowerCase().includes(needle))&&(category==="Tous"||row.category===category)&&(classFilter==="Toutes"||row.classLevel===classFilter)&&(qualification==="Toutes"||Boolean(selected))&&(state==="Tous"||(state==="Actifs"&&row.status==="Actif")||(state==="Expire bientôt"&&flags.expiring)||(state==="Expiré"&&flags.expired)||(state==="Élément manquant"&&flags.missing))}),[rows,query,category,state,classFilter,qualification]);
 const displayed=(row:StaffRow)=>[...row.qualifications,...row.training] as EmployeeQualification[];
 const expired=rows.reduce((sum,row)=>sum+displayed(row).filter(item=>item.status==="expired").length,0),expiring=rows.reduce((sum,row)=>sum+displayed(row).filter(item=>item.status==="expiring").length,0),missing=rows.reduce((sum,row)=>sum+displayed(row).filter(item=>item.status==="missing").length,0);
 return <section className="employee-workspace staff-overview"><section className="card employee-section-head"><div><h2>Tableau conformité du personnel</h2><p>Les formations correspondent directement au dossier Employés → Formations. Survolez un indicateur pour voir son état et son échéance.</p></div></section>{error&&<div className="notice error">{error}</div>}
  <section className="staff-kpis"><article className="card"><span>Total employés</span><strong>{rows.length}</strong></article><article className="card"><span>Instructeurs actifs</span><strong>{rows.filter(row=>row.category==="Instructeurs"&&row.status==="Actif").length}</strong></article><article className="card ok"><span>Médicaux valides</span><strong>{rows.filter(row=>qualificationFor(row,"Médical")?.status==="valid").length}</strong></article><article className="card warn"><span>Échéances &lt; 90 jours</span><strong>{expiring}</strong></article><article className="card danger"><span>Éléments expirés</span><strong>{expired}</strong></article><article className="card neutral"><span>Éléments manquants</span><strong>{missing}</strong></article><article className="card"><span>Absents / en congé</span><strong>{rows.filter(row=>row.absent||row.status==="Congé").length}</strong></article></section>
  <section className="card staff-filters"><input aria-label="Rechercher par nom" placeholder="Rechercher par nom…" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Rôle" value={category} onChange={event=>setCategory(event.target.value as typeof category)}><option>Tous</option><option>Instructeurs</option><option>Maintenance</option><option>Administration</option><option>Dispatch</option><option>Autre</option></select><select aria-label="Statut de conformité" value={state} onChange={event=>setState(event.target.value as typeof state)}><option>Tous</option><option>Actifs</option><option>Expire bientôt</option><option>Expiré</option><option>Élément manquant</option></select><select aria-label="Classe" value={classFilter} onChange={event=>setClassFilter(event.target.value)}><option>Toutes</option><option>Classe 1</option><option>Classe 2</option><option>Classe 3</option><option>Classe 4</option></select><select aria-label="Élément de conformité" value={qualification} onChange={event=>setQualification(event.target.value)}><option>Toutes</option>{complianceOptions.map(item=><option key={item}>{item}</option>)}</select></section>
  <section className="card staff-table-card"><div className="staff-table-wrap"><table className="staff-table"><thead><tr className="staff-group-head"><th rowSpan={2}>Nom</th><th rowSpan={2}>Poste / rôle</th><th rowSpan={2}>Classe</th><th rowSpan={2}>Statut</th><th rowSpan={2}>Médical</th><th rowSpan={2}>Classe instructeur</th><th colSpan={EMPLOYEE_TRAINING_SUBJECTS.length}>Formations obligatoires</th><th colSpan={qualificationColumns.length}>Avions / qualifications</th><th rowSpan={2}>Prochaine échéance</th><th rowSpan={2}>Action</th></tr><tr>{EMPLOYEE_TRAINING_SUBJECTS.map(subject=><th className="staff-vertical-head" key={subject.id} title={subject.label}><span>{trainingShort[subject.id]||subject.label}</span></th>)}{qualificationColumns.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{visible.map(row=>{const isInstructor=row.category==="Instructeurs",medical=qualificationFor(row,"Médical"),instructorClass=row.qualifications.find(item=>item.qualificationType==="instructor-class");return <tr key={row.id} tabIndex={0} onClick={()=>onOpenEmployee(row.id,isInstructor)} onKeyDown={event=>{if(event.key==="Enter")onOpenEmployee(row.id,isInstructor)}}><td><button className="staff-name" onClick={()=>onOpenEmployee(row.id,isInstructor)}>{row.name}</button></td><td>{row.role}</td><td>{row.classLevel}</td><td><span className={`badge ${row.status==="Actif"?"ok":row.status==="Congé"?"warn":""}`}>{row.absent?"Absent":row.status}</span></td><td><ComplianceBadge item={medical} applicable={isInstructor||Boolean(medical)}/></td><td>{instructorClass?<span className="staff-class-valid">{instructorClass.qualificationName} — Valide</span>:<ComplianceBadge compact applicable={false}/>}</td>{row.training.map(item=><td className="staff-indicator-cell" key={item.id}><ComplianceBadge item={item} compact/></td>)}{qualificationColumns.map(name=><td className="staff-indicator-cell" key={name}><ComplianceBadge item={qualificationFor(row,name)} compact applicable={Boolean(qualificationFor(row,name))}/></td>)}<td><Deadline value={row.nextDeadline}/></td><td><button className="button secondary small" onClick={event=>{event.stopPropagation();onOpenEmployee(row.id,isInstructor)}}>Voir la fiche</button></td></tr>})}</tbody></table></div>{!visible.length&&<p className="staff-empty">Aucun employé ne correspond aux filtres.</p>}</section></section>;
}
