"use client";
import {useEffect,useMemo,useState} from "react";
import {useAuth} from "@/features/auth/AuthProvider";
import {requestTimeEntryCorrection,reviewTimeEntryPeriod,submitTimeEntryPeriod,subscribePayrollClassRates,subscribePayrollProfiles,subscribeTimeEntries,type PayrollReviewAction} from "./firestore";
import{subscribeInstructors}from"@/features/instructors/firestore";
import type{Instructor}from"@/features/instructors/types";
import{payrollEntrySnapshot}from"./payrollRates";
import type {EmployeePayrollProfile,PayrollActor,PayrollClassRate,TimeEntry} from "./types";

type Props={mode:"employee"|"admin"};
const money=(value:number)=>value.toLocaleString("fr-CA",{style:"currency",currency:"CAD"});
const periodLabel=(id:string)=>id.startsWith("parallel-")?id.slice(9):id;
const sourceLabel=(entry:TimeEntry)=>entry.source==="scheduler"?entry.sourceComponent==="adjustment"?"Ajustement Scheduler":"Scheduler":entry.source;

export function TimeEntriesValidationPanel({mode}:Props){
 const{user,profile}=useAuth(),manager=profile?.role==="Administrateur"||profile?.role==="Chef instructeur";
 const employeeId=profile?.linkedInstructorId||user?.uid||"";
 const[entries,setEntries]=useState<TimeEntry[]>([]),[profiles,setProfiles]=useState<EmployeePayrollProfile[]>([]),[rates,setRates]=useState<PayrollClassRate[]>([]),[instructors,setInstructors]=useState<Instructor[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const[correction,setCorrection]=useState<{id:string;comment:string}|null>(null),[review,setReview]=useState<{employeeId:string;periodId:string;action:PayrollReviewAction;reason:string}|null>(null);
 useEffect(()=>{if(mode==="employee"&&!employeeId){setEntries([]);return;}return subscribeTimeEntries(mode==="admin"?undefined:employeeId,mode==="admin",setEntries,value=>setError(value.message));},[employeeId,mode]);
 useEffect(()=>{if(mode==="employee"&&!employeeId){setProfiles([]);return;}return subscribePayrollProfiles(mode==="admin"?undefined:employeeId,mode==="admin",setProfiles,value=>setError(value.message));},[employeeId,mode]);
 useEffect(()=>subscribePayrollClassRates(setRates,value=>setError(value.message)),[]);useEffect(()=>subscribeInstructors({next:setInstructors,error:value=>setError(value.message)}),[]);
 const estimate=(entry:TimeEntry,employeeProfile:EmployeePayrollProfile|undefined)=>payrollEntrySnapshot(entry,employeeProfile,rates,instructors.find(item=>item.id===entry.employeeId));
 const actor:PayrollActor={uid:user?.uid||"",name:profile?.name||profile?.email||"Utilisateur",role:profile?.role||""};
 const groups=useMemo(()=>{const map=new Map<string,TimeEntry[]>();for(const entry of entries){const key=`${entry.employeeId}|${entry.payPeriodId}`;map.set(key,[...(map.get(key)||[]),entry]);}return[...map.values()].sort((a,b)=>b[0].workDate.localeCompare(a[0].workDate)||a[0].employeeName.localeCompare(b[0].employeeName));},[entries]);
 const run=async(task:()=>Promise<void>,success:string)=>{setBusy(true);setError("");try{await task();setMessage(success);return true;}catch(value){setError(value instanceof Error?value.message:"Opération impossible.");return false;}finally{setBusy(false)}};
 const submit=(items:TimeEntry[])=>run(()=>submitTimeEntryPeriod(items[0].employeeId,items[0].payPeriodId,actor),"Période soumise à l’administration.");
 const confirmCorrection=async()=>{if(!correction)return;const current=correction;if(await run(()=>requestTimeEntryCorrection(current.id,actor,current.comment),"Demande de correction enregistrée."))setCorrection(null);};
 const confirmReview=async()=>{if(!review)return;const current=review,items=entries.filter(item=>item.employeeId===current.employeeId&&item.payPeriodId===current.periodId),snapshots=Object.fromEntries(items.map(item=>{const value=estimate(item,profiles.find(p=>p.employeeId===item.employeeId));return[item.id,{rate:value.rate,bonus:value.bonus,amount:value.amount}]}));if(await run(()=>reviewTimeEntryPeriod(current.employeeId,current.periodId,current.action,actor,current.reason,snapshots),current.action==="approve"?"Période approuvée.":"Décision enregistrée."))setReview(null);};
 if(mode==="admin"&&!manager)return <div className="notice error">Accès réservé à l’administration de la paie.</div>;
 if(mode==="employee"&&!employeeId)return <div className="notice warn">Votre identité employé n’est pas encore disponible. Reconnectez-vous puis réessayez.</div>;
 return <section className="employee-workspace payroll-validation">
  <div className="card employee-section-head"><div><h2>{mode==="admin"?"Validation paie":"Mes heures"}</h2><p>{mode==="admin"?"Contrôle administratif des périodes soumises.":"Registre issu des activités réellement complétées dans Scheduler."}</p></div></div>
  {error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
  {groups.map(items=>{const first=items[0],payrollProfile=profiles.find(item=>item.employeeId===first.employeeId),hours=Math.round(items.reduce((sum,item)=>sum+item.durationHours,0)*10)/10,total=items.reduce((sum,item)=>sum+estimate(item,payrollProfile).amount,0),statuses=[...new Set(items.map(item=>item.status))],hasDraft=items.some(item=>item.status==="Brouillon"||item.status==="Ajustement"),hasSubmitted=items.some(item=>item.status==="Soumis employé");return <article className="card payroll-period" key={`${first.employeeId}-${first.payPeriodId}`}>
   <header><div><h3>{mode==="admin"&&<>{first.employeeName} · </>}Période {periodLabel(first.payPeriodId)}</h3><span>{hours.toFixed(1)} h · {money(total)}</span></div><div className="payroll-statuses">{statuses.map(status=><span className={`badge ${status==="Refusé"||status==="Correction requise"?"warn":status==="Approuvé administration"||status==="Verrouillé"?"ok":""}`} key={status}>{status}</span>)}</div></header>
   <div className="payroll-entry-table"><div className="payroll-entry-row head"><span>Date</span><span>Activité</span><span>Catégorie</span><span>Durée</span><span>Source</span><span>Estimation</span><span>État</span><span>Action</span></div>{items.map(item=>{const value=estimate(item,payrollProfile);return <div className="payroll-entry-row" key={item.id}><span>{new Date(`${item.workDate}T12:00:00`).toLocaleDateString("fr-CA")}</span><span>{item.description||item.activityType||"Activité"}</span><span>{item.category}</span><strong>{item.durationHours.toFixed(1)} h</strong><span>{sourceLabel(item)}</span><span>{money(value.amount)}</span><span>{item.status}</span><span>{mode==="employee"&&["Brouillon","Soumis employé"].includes(item.status)?<button className="button secondary small" onClick={()=>setCorrection({id:item.id,comment:""})}>Demander correction</button>:"—"}</span></div>})}</div>
   <footer>{mode==="employee"&&hasDraft&&<button className="button" disabled={busy} onClick={()=>submit(items)}>Soumettre ma période</button>}{mode==="admin"&&hasSubmitted&&<><button className="button" disabled={busy} onClick={()=>setReview({employeeId:first.employeeId,periodId:first.payPeriodId,action:"approve",reason:""})}>Approuver</button><button className="button secondary" disabled={busy} onClick={()=>setReview({employeeId:first.employeeId,periodId:first.payPeriodId,action:"correction",reason:""})}>Retourner pour correction</button><button className="button danger" disabled={busy} onClick={()=>setReview({employeeId:first.employeeId,periodId:first.payPeriodId,action:"refuse",reason:""})}>Refuser</button></>}</footer>
  </article>})}
  {!groups.length&&<div className="card"><p>{mode==="admin"?"Aucune période disponible.":"Aucune activité complétée n’a encore alimenté votre registre."}</p></div>}
  {correction&&<div className="modal-overlay"><section className="modal-card payroll-dialog"><header><h2>Demander une correction</h2><button onClick={()=>setCorrection(null)}>×</button></header>{error&&<div className="notice error">{error}</div>}<label>Commentaire obligatoire<textarea rows={5} autoFocus value={correction.comment} onChange={event=>setCorrection({...correction,comment:event.target.value})}/></label><footer><button className="button secondary" onClick={()=>setCorrection(null)}>Annuler</button><button className="button" disabled={busy||!correction.comment.trim()} onClick={confirmCorrection}>Envoyer</button></footer></section></div>}
  {review&&<div className="modal-overlay"><section className="modal-card payroll-dialog"><header><h2>{review.action==="approve"?"Approuver la période":review.action==="correction"?"Retourner pour correction":"Refuser la période"}</h2><button onClick={()=>setReview(null)}>×</button></header>{error&&<div className="notice error">{error}</div>}<label>Raison obligatoire<textarea rows={5} autoFocus value={review.reason} onChange={event=>setReview({...review,reason:event.target.value})}/></label><footer><button className="button secondary" onClick={()=>setReview(null)}>Annuler</button><button className="button" disabled={busy||!review.reason.trim()} onClick={confirmReview}>Confirmer</button></footer></section></div>}
  <style jsx global>{`.payroll-validation{position:relative}.payroll-period{display:grid;gap:14px;overflow:hidden}.payroll-period>header{display:flex;align-items:center;justify-content:space-between;gap:16px}.payroll-period h3{margin:0 0 5px}.payroll-statuses,.payroll-period>footer{display:flex;gap:8px;flex-wrap:wrap}.payroll-period>footer{justify-content:flex-end}.payroll-entry-table{overflow-x:auto}.payroll-entry-row{display:grid;grid-template-columns:105px minmax(190px,1fr) 150px 75px 125px 100px 165px 150px;gap:10px;align-items:center;padding:10px 8px;border-bottom:1px solid var(--border);min-width:1120px}.payroll-entry-row.head{background:#edf4fb;color:#214e78;font-weight:800}.payroll-dialog{z-index:10001;display:grid;gap:16px;max-width:560px}.payroll-dialog header,.payroll-dialog footer{display:flex;align-items:center;justify-content:space-between;gap:12px}.payroll-dialog header h2{margin:0}.payroll-dialog header button{border:0;border-radius:50%;font-size:26px;width:42px;height:42px}.payroll-dialog footer{justify-content:flex-end}`}</style>
 </section>;
}
